export const posterParadeItems = [
  {
    name: 'Zur Jugend',
    caption:
      'Unter Jugend versteht man die Lebensphase zwischen Kindheit und Erwachsensein. Wegen ihrer Länge wird die Lebensphase Jugend auch oft in Abschnitte untergliedert. Der erste Abschnitt bis zum Alter von 18 Jahren wird als Adoleszenz bezeichnet, wobei bei juristischen Auseinandersetzungen das Jugendrecht zum Tragen kommt.',
    contentPosition: 'left',
    items: [
      {
        image: '/posterParade/youth.webp',
        href: 'youth',
      },
      {
        image: '/posterParade/youth2.webp',
        href: 'youth2',
      },
    ],
  },
  {
    name: 'Zum Frieden',
    caption:
      'Frieden ist allgemein definiert als ein heilsamer Zustand der Stille oder Ruhe, als die Abwesenheit von Störung oder Beunruhigung und besonders von Krieg. Frieden ist das Ergebnis der Tugend der „Friedfertigkeit“ und damit verbundener Friedensbemühungen.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/peace.webp',
        href: 'peace',
      },
      {
        image: '/posterParade/peace2.webp',
        href: 'peace2',
      },
    ],
  },
  {
    name: 'Bildanalysen',
    caption: 'zur Demokratie',
    contentPosition: 'right',
    items: [
      {
        image: '/posterParade/peace3.webp',
        href: 'peace3',
      },
      {
        image: '/posterParade/democracy.webp',
        href: 'democracy',
      },
    ],
  },
  {
    name: 'Bildanalyse',
    caption: 'zur Solidarität',
    contentPosition: 'left',
    items: [
      {
        image: '/posterParade/solidarity.webp',
        href: 'solidarity',
      },
      {
        image: '/posterParade/solidarity2.webp',
        href: 'solidarity2',
      },
    ],
  },
  {
    name: 'Bildanalysen zum Thema Antifaschismus',
    caption: 'Antifaschismus spielte für die Arbeiter:innenjugendbewegung schon seit den frühen 1920er Jahren eine wichtige Rolle.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/antifascism.webp',
        href: 'antifascism',
      },
      {
        image: '/posterParade/antifascism2.webp',
        href: 'antifascism2',
      },
    ],
  },
  {
    name: 'Bildanalyse',
    caption: 'zur Umwelt',
    contentPosition: 'right',
    items: [
      {
        image: '/posterParade/youth3.webp',
        href: 'youth3',
      },
      {
        image: '/posterParade/environment.webp',
        href: 'environment',
      },
    ],
  },
  {
    name: 'Bildanalyse',
    caption: 'zum Antirassismus',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/antirascism.webp',
        href: 'antirascism',
      },
      {
        image: '/posterParade/democracy.webp',
        href: 'democracy',
      },
    ],
  },
]

export const posterParadeTexts = {
  antifascism: {
    header: 'Bildanalyse Antifaschismus',
    texts: [
      'Die Zeile „Der Schoß ist fruchtbar noch…“ stammt aus Theaterstück »Der aufhaltsame Aufstieg des Arturo Ui« von Bertolt Brecht.',
      'Darin geht es parabelhaft um den Aufstieg Adolf Hitlers.',
      'Der Epilog des Stückes endet mit den Worten:',
      '„So was hätt einmal fast die Welt regiert! Die Völker wurden seiner Herr, jedoch Dass keiner uns zu früh da triumphiert - Der Schoß ist fruchtbar noch, aus dem das kroch!“',
      'Der Halbsatz „Nie wieder!“ gilt als ein Willy Brandt zugeschriebenes Zitat, dass von deutschem Boden nie wieder Krieg ausgehen dürfe.',
      '„Nie wieder!“ gilt im allgemeinen Sprachgebrauch aber auch generell für die Forderung, dass sich etwas wie der Holocaust und der Zweite Weltkrieg nicht wiederholen dürfen.',
      'Das Foto zeigt exemplarisch die Verbrechen der deutschen Nationalsozialisten anhand von Leichen, die die Alliierten nach Kriegsende im Konzentrations- und Vernichtungslager Auschwitz fanden (oder anderes Lager im Bild???).',
      'Solche Bilder symbolisierten oft das unmenschliche Leid, dass Menschen durch andere Menschen aufgrund ihrer Herkunft, ihres Glaubens, ihrer Sexualität usw. angetan wurde.',
      'Dieses Bild symbolisiert also die Opfer nationalsozialistischer Herrschaft.',
      'Ergänzend zeigt das nebenstehende Foto die symbolisch die Täter nationalsozialistischer Herrschaft:',
      'ein Angehöriger der Leibstandarte Adolf Hitler, der eine Trompete, vermutlich anlässlich eines Aufmarsches oder Appells spielt.',
      'Dieser paramilitärische Verband spielte eine relevante Rolle bei der Niederschlagung des Röhm-Putsches und den damit verbundenen Tötungen von SA-Mitlgiedern.',
      'Der rote Blitz markiert symbolisch das Ende des Zweiten Weltkrieges und des Faschismus.',
      'Er erinnert aber auch an die spezielle Rolle, die der Kommunismus in der Gestalt von Stalin und der Sowjetunion dabei spielt.',
      'In der unteren Bildreihe sieht man Fotografien aus der Zeit nach dem Zweiten Weltkrieg.',
      'Das erste Foto zeigt eine Gruppe von Neonazis in den 1950er Jahren mit Hakenkreuz, dem Symbol des deutschen Nationalsozialismus, im Hintergrund.',
      'Alle zeigen den Hitlergruß.',
      'In dem Bild sieht man einen trommelnden Jungen vor Fahnen mit dem Othala-Symbol.',
      'Othala ist die germanische Rune und bedeutet wahrscheinlich Erbbesitz, Heimat.',
      'In abgewandelter Form wurde dieses Symbol sowohl von der 7. SS-Freiwilligen-Gebirgs-Division „Prinz Eugen“, der Hitler-Jugend (HJ) und dem Rasse- und Siedlungshauptamt als Kennzeichen genutzt.',
      'Nach 1945 nutzen ebenfalls verschiedene nationalistische und neonazistische Verbände dieses Symbol in diversen Erscheinungsformen.',
      'Das Plakat stammt vom sozialistischen Jugendverband „SJD - Die Falken“.',
      'Dabei steht „SJD“ für Sozialistische Jugend Deutschlands.',
      'Dieser der SPD-nahestehende Verband trat seit den 1920er Jahren gegen Faschismus, Nationalismus und Krieg ein.',
    ],
  },
  antifascism2: {
    header: '',
    texts: [
      'Das Erscheinungsbild der deutschen Soldaten im Zweiten Weltkrieg wurde vor allem durch die Marschstiefel geprägt.',
      'In der nationalsozialistischen Propaganda wurde eine permanente Assoziation zwischen den Stiefeln, dem Marschieren und den Paraden geschaffen.',
      'Die Intention dieser Assoziation war es ein Bild zu erschaffen, das die marschierenden Soldaten mit der Idee der geografischen Erweiterung verknüpft.',
      'Demnach sind die Marschstiefel in diesem Kontext nicht bloß ein Kleidungsstück der Soldaten, sondern sind ein propagandiertes Symbol für die Eroberungspläne des nationalsozialistischen Regimes.',
      'An dieser Stelle sind drei Hände zu sehen, die den Stiefel, als Symbol für die nationalsozialistische Herrschaft, wegdrücken.',
      'Die erhobenen geballten Fäuste sind ein Symbol für Solidarität, Stärke und den Befreiungskampf. Im Laufe der Geschichte haben sich viele verschiedene soziale Bewegungen die erhobene Faust zu eigen gemacht.',
      'Der Begriff „Reichskristallnacht“ ist eine veraltete Bezeichnung für die Novemberpogrome, welche vor allem in der Nacht vom 9.11.1938 auf den 10.11.1938 und in den Folgetagen im Deutschen Reich und im annektierten Österreich stattfanden.',
      'Die verharmlosende und euphemistische Bezeichnung „Reichkristallnacht“ ist auf die vielen Fensterglasscherben der zerstörten Wohnungen und Geschäfte jüdischer Bürger:innen zurück zu führen, weswegen der Begriff als problematisch gilt und heute durch die Begriffe „Novemberpogrome“ oder „Reichspogromnacht“ ersetzt wurde.',
      'Die Aktionen waren von oben angeordnet und wurden kurz nach dem Bekanntwerden des Attentats auf Ernst vom Rath initiiert. Dieses Attentat nutzte das nationalsozialistische Regime als rechtfertigenden Anlass für die Zerstörung jüdischen Eigentums sowie für die körperliche Misshandlung und Ermordung jüdischer Mitmenschen.',
      'In diesem Zeitraum haben Schlägertrupps des nationalsozialistischen Regimes Synagogen, jüdische Geschäfte und Wohnungen zerstört und in Brand gesetzt.',
      'Jüdisch gelesene Menschen wurden körperlich misshandelt, ermordet und in Konzentrationslager deportiert. Die Novemberpogrome gelten als radikalisierter Wendepunkt von der Diskriminierung der jüdischen Bevölkerung ab 1933 hin zur systematischen Vertreibung und Ermordung derselben.',
      'Zum 30-jährigen Gedenken trägt das Plakat die Überschrift „Nie wieder Reichskristallnacht“ und lud zu einem Fackelzug und einer Kundgebung am Platz der ehemaligen Synagoge in Gelsenkirchen ein.',
      'Der ehemalige SPD-Bundestagsabgeordnete Klaus Thüsing hielt anlässlich dessen eine Rede.',
      'Es stellt sich die Frage: Ist in diesem Kontext ein Fackelzug angebracht oder doch eher problematisch?',
      'Die Herausgeberin des Plakates ist die Sozialistische Jugend Deutschlands – Die Falken – Unterbezirk Gelsenkirchen. Die Falken setzen sich für mehr Demokratie, soziale Gerechtigkeit, Selbstbestimmung und Frieden für alle ein.',
    ],
  },
  antirascism: {
    header: '',
    texts: [],
  },
  democracy: {
    header: '',
    texts: [],
  },
  environment: {
    header: '',
    texts: [
      'Die im Jahr 1986 geschehenen Störfälle im Thorium-Hoch-Temperatur-Reaktor (THTR) markierten einen Wendepunkt in der Geschichte des Widerstandes gegen den THTR.',
      'Insgesamt beteiligten sich bei dieser Demonstration rund 3000 Bürger:innen, die gegen das THTR demonstrierten. Der Großteil der Demonstrant:innen stammte aus Hamm, das überregionale Interesse hielt sich in Grenzen.',
      'Dennoch galt die Demonstration als ein großer Erfolg.',
      'Zu sehen ist eine „Bierhalle“, wie sie typisch fürs Ruhrgebiet ist. Die Aufschrift „Isenbeck“ lokalisiert abermals den Standort, da das Pils in Hamm und Umgebung eine lokale Premium-Marke ist.',
      'Das Plakat stammt von der Bürgerinitiative Umweltschutz e.V. und ruft zu einer Demonstration gegen das Atomkraftwerk in Hamm-Werries am 17.09.1986 auf.',
      'Einige Zeit zuvor kam es mit der Nuklearkatastrophe von Tschernobyl am 26.04.1986 zur größten nuklearen Havarie des 20. Jahrhunderts.',
      'Kurz darauf, am 04.05.1986, drang aus dem Reaktor in Hamm radioaktiver Grafitstaub in die Umgebungsluft. Dieser Vorfall wäre meldepflichtig gewesen, wurde allerdings nicht gemeldet, in der Hoffnung man könne diesen Vorfall verschweigen.',
      'Wie viel strahlendes Material ausgetreten ist, lässt sich nicht nachvollziehen, da zu diesem Zeitpunkt das Messinstrument abgeschaltet war.',
      'Nebenbei bemerkt: Fällt den aufmerksamen Leser:innen dieses Plakates der Druckfehler in "Demonstration" auf?',
      'Grafisch dargestellt ist hier der Thorium-Hoch-Temperatur-Reaktor, kurz THTR-300, im nordrhein-westfälischen Hamm/Uentrop, aus dessen Wolke ein Totenkopf emporsteigt.',
      'Die Bauarbeiten am Kernkraftwerk THTR-300 begannen 1970 und wurden 1985 beendet. Anstelle von Brennstäben wurden in diesem Reaktor Graphitkugeln verwendet – damit wurde dem Prototypen AVR Jülich gefolgt, welcher 1967 in Betrieb ging.',
      'Bereits am AVR Jülich kam es 1978 zu einem Störfall. Im THTR häuften sich etliche nicht meldepflichtige und 21 meldepflichtige Vorfälle.',
      'Der dabei entstandene Kugelbruch beziehungsweise radioaktiver Grafitstaub befindet sich gegenwärtig immer noch in unbekannter Menge im Reaktor, erschwert den Rückbau des AKWs enorm und erhöht die Kosten.',
    ],
  },
  peace: {
    header: 'Bildanalyse Frieden',
    texts: ['Text 1', 'Text 2', 'Text 3', 'Text 4', 'Text 5', 'Text 6', 'Text 7', 'Text 8', 'Text 9'],
  },
  peace2: {
    header: 'Bildanalyse 6 vor 12',
    texts: [
      'Am 21./22. November 1983 wurde im Deutschen Bundestag über die Stationierung von 108 Pershing II-Raketen und 96 Marschflugkörpern auf dem Territorium der BRD entschieden.',
      'Die CDU/CSU hatte gemeinsam mit der FDP angekündigt, der Stationierung neuer Atomwaffen in der BRD zuzustimmen, was sie schließlich auch taten.',
      'Die abgebildeten Abgeordneten stehen auf diesem Plakat stellvertretend für jene, die der Stationierung zugestimmt hatten.',
      'Herbert Werner wurde 1941 in Teplitz (Böhmen) geboren. Nach einem Englisch- und Geschichtsstudium war er als Studienrat und später als Oberstudienrat tätig.',
      'Im Jahr 1969 trat Herbert Werner in die CDU ein. Von 1972 bis 1994 vertrat er den Wahlkreis Ulm im Deutschen Bundestag.',
      'Hermann Schwörer wurde 1922 in Oberstetten (Württemberg) geboren.',
      'Nach einem durch den Kriegseinsatz im Zweiten Weltkrieg unterbrochenen Studium der Rechts- und Staatswissenschaften promovierte er 1950 und trat im selben Jahr in den familieneigenen Baustoffbetrieb ein.',
      'Im Jahr 1951 folgte der Eintritt in die CDU, für die er ab 1958 als Abgeordneter im Bundestag saß.',
      'Er engagierte er sich unter anderem seit November 1958 im Ausschuss für Atomkernenergie und Wasserwirtschaft.',
      'Manfred Abelein wurde 1930 in Stuttgart geboren. Nach dem Studium der Rechtswissenschaft, Volkswirtschaft und Politikwissenschaft promovierte er 1954 an der Universität Basel.',
      'Als CDU-Abgeordneter des Wahlkreises Aalen-Heidenheim gehörte er von 1965 bis 1990 dem Bundestag an.',
      'Elmar Kolb wurde 1936 in Bad Neustadt (Saale) geboren. Nach einer kaufmännische Lehre und einem Maschinenbaustudium in Nürnberg trat er 1965 der Jungen Union bei.',
      'Seit 1967 war er Mitglied der CDU. Seit 1969 gehörte Elmar Kolb dem Bezirksvorstand der CDU Süd-Württemberg-Hohenzollern an.',
      'Seit 1977 saß er als Abgeordneter im Deutschen Bundestag, wo er unter anderem seit 1986 dem Ausschuss für Umwelt, Naturschutz und Reaktorsicherheit angehörte.',
      'Hans-Peter Repnik wurde 1947 in Konstanz geboren. Nach Studium der Rechts- und Staatswissenschaften engagierte er sich zunächst in der Jungen Union.',
      'Von 1989 bis 1994 war er Parlamentarischer Staatssekretär beim Bundesminister für wirtschaftliche Zusammenarbeit und Entwicklung.',
      'Zwischen 1980 und 2005 vertrat er den Wahlkreis Konstanz im Bundestag. Hans-Peter Repnik war von 2010 bis 2012 Mitglied und Vorsitzender des Rates für Nachhaltige Entwicklung.',
      'Der Atompilz der „Fat Man“ genannten Bombe, die am 09.08.1945 über Nagasaki abgeworfen wurde, ist zum Sinnbild für die US-amerikanischen Atombombenabwürfe auf Hiroshima und Nagasaki sowie die atomare Zerstörung geworden.',
      'Insgesamt töteten die Explosionen circa 100.000 Menschen. An den Folgeschäden starben allein bis Ende 1945 weitere 130.000 Menschen.',
      'Den Befehl zum Abwurf der Atombomben gab der amerikanische Präsident Harry S. Truman.',
      'Am 02.09.1945 endete der Zweite Weltkrieg mit der Kapitulation Japans auch in Asien.',
      'Trotz der Atombombenabwürfe auf Hiroshima und Nagasaki entstand durch propagandistische Trennung zwischen ziviler und militärischer Atomenergienutzung eine Gleichzeitigkeit von Atomeuphorie und Atomangst.',
      'Die metaphorische Weltuntergangsuhr beziehungsweise Atomkriegsuhr soll der Öffentlichkeit verdeutlichen, wie groß das Risiko einer globalen Katastrophe insbesondere im Hinblick auf einen Atomkrieg oder einer Klimakatastrophe ist.',
      'Die im Fokus dieses Plakats stehenden Porträts der Politiker haben allesamt eine Zahl im rechten unteren Winkel vermerkt.',
      'Diese Zahlen symbolisieren das Herunterzählen von eins bis sechs, wobei Bild sechs die atomare Katastrophe in Form des Atompilzes verdeutlicht.',
    ],
  },
  peace3: {
    header: '',
    texts: [
      'Hier ist eine demonstrierende Menschenmenge abgebildet. Der hier thematisierte Protest kritisiert den NATO-Doppelbeschluss, welcher in insbesondere in der BRD für Konflikte und Großdemonstrationen sorgte.',
      'Auch wenn zumeist die jüngere Generation die Mehrheit bei solchen Demonstrationen bzw. Ostermärschen bildete, sind häufig viele Altersgruppen sowie alle sozialen Klassen vertreten.',
      'Typisch für die Ostermärsche sind die hier abgebildeten Fahnen und Schilder mit der symbolischen Friedenstaube oder kurzen Leitsprüchen wie „Nein zu Atom“.',
      'Der erste Ostermarsch in Deutschland fand im Jahr 1960 statt und führte als mehrtägiger Marsch von Hamburg über Bremen, Hannover und Braunschweig nach Bergen-Hohne.',
      'Ziel war das Raketenübungsgelände der Bundeswehr, wo Berichten zufolge eine Batterie Honest-John-Raketen mit atomaren Sprengköpfen stationiert worden war.',
      'Hieran nahmen circa 120 Teilnehmer:innen teil. Fortan kam es zu bundesweiten, sich jährlich wiederholenden Ostermärschen. Die Grundgedanken der Ostermärsche sind pazifistisch und antimilitaristisch.',
      'Ausgehend von der Friedensbewegung finden alljährlich mehrtägige Kundgebungen und Demonstrationen bundesweit statt, die für Frieden und gegen Waffen plädieren.',
      'In den Jahren von 1979 bis 1990 kam es durch den NATO-Doppelbeschluss zu einem neuen Aufschwung der Ostermärsche.',
      'Im Fall dieses Plakates, also im Jahr 1984, nahmen bundesweit circa 600.000 Menschen an Ostermarsch-Kundgebungen für Abrüstung und Frieden teil.',
      'Die Rakete Pershing II, benannt nach dem US-General John Joseph Pershing, war das Nachfolgemodel der Pershing I. In Westdeutschland begann wenige Tage nach der Zustimmung des Deutschen Bundestag am 22.11.1983 die Stationierung der Pershing II.',
      'Auf diesem Banner ist deutlich der Spruch „Stoppt den Rüstungswahn“ zu lesen. Dieser Leitspruch wurde und wird häufig bei pazifistischen und antimilitaristischen Demonstrationen und Ostermärschen genutzt.',
      'Seit 1970 wurden die Pershing II und Cruise Missiles entwickelt. Sie galten als „Innovation“, da sie als treffgenau galten und eine flexible Reichweite boten.',
      'Im Dezember 1979 wurde von den Außen- und Verteidigungsministern der NATO-Mitgliedstaaten in Brüssel beschlossen, die Pershing II als auch die Cruise Missiles in Europa zu stationieren.',
      'Zeitgleich sollten der Sowjetunion aber Verhandlungen über eine beidseitige Reduzierung nuklearer Waffen angeboten werden.',
      'Dieses karikative Abbild zeigt den damaligen deutschen Bundeskanzler Helmut Kohl. Helmut Kohl, geboren l930 und gestorben 2017, führte von 1982 bis 1998 als sechster Bundeskanzler der Bundesrepublik Deutschland eine CDU/CSU/FDP Koalition.',
      'Kohl war Gegenstand unzähliger Karikaturen. In diesem Plakat ist er als „Eierkopf“ dargestellt, eine umgangssprachliche Bezeichnung, die abwertend oder ironisch für Intellektuelle genutzt wird.',
      'Ein Demonstrant tritt Helmut Kohl, dargestellt als „Eierkopf“, ins Gesicht, woraufhin seine „Schale“ anfängt aufzubrechen - sinnbildlich für den gedanklichen Widerstand innerhalb der Bevölkerung.',
      'An dieser Stelle wird über den Ablauf des Ostermarsches informiert: Angefangen mit einer Blockade der US-Kaserne in der Garlstedter Heide vor Ostern, ist für den Ostersonntag ein Ostermarsch von Neuengamme (Standort eines ehemaligen Konzentrationslagers) nach Hamburg geplant.',
      'Es folgen Sternmärsche aus allen Hamburger Stadtteilen zum Rathausmarkt. Bei Sternmärschen kommen Demonstrierende von verschiedenen Ausgangspunkten zu einem gemeinsamen Endziel zusammen. Daraufhin erfolgt eine Abschlusskundgebung.',
      'Zwischen Ostern und dem 1. Mai ist dann eine Aktionswoche betrieblicher Friedensinitiativen geplant.',
      'Das Plakat stammt von den Jungsozialist:innen der SPD. Sie positionieren sich explizit gegen die Stationierung von Atomwaffen und sind grundlegend gegen eine Rüstungspolitik.',
      'An dieser Stelle rufen sie die Bevölkerung dazu auf, aktiv zu werden und bei den Ostermärschen mitzumachen.',
    ],
  },
  solidarity: {
    header: '',
    texts: [
      '„Freiheit für alle politischen Gefangenen in Chile!“ - Nach dem Putsch am 11.09.1973 gegen den gewählten Präsidenten Salvador Allende begann unter Augusto Pinochet eine brutale Diktatur.',
      'Das Militär hatte binnen kürzester Zeit das Land unter seine Kontrolle gebracht. Mehr als 27.000 (vermeintlich) Regimegegner:innen wurden verfolgt, gefangen genommen und gefoltert.',
      'An dieser Stelle ist eine „Friedenstaube“ abgebildet. Ursprünglich geht das Symbol der Friedenstaube auf die Geschichte Noahs im Alten Testament zurück.',
      'Im Zentrum dieses Plakates steht allerdings die grafische Form der Friedenstaube, die auf Pablo Picassos Werk basiert.',
      'Picasso, engagiertes Mitglied der kommunistischen Partei, gestaltete mit der Friedenstaube Plakate in Wrocław, Paris, Stockholm, Sheffield und Rom. Während des Kalten Krieges wurde die Friedenstaube auf diesem Weg zum wichtigsten Hoffnungssymbol.',
      'Er unterstützte mit verschiedenen Varianten dieses Motivs die kommunistische Partei in Frankreich, anderen Ländern und radikalen Organisationen in Westeuropa.',
      'Mit seinen Arbeiten drückte Picasso seine eigene politische Haltung künstlerisch aus, propagierte für die Friedensbewegung und protestierte gegen Krieg und Unterdrückung.',
      'In jüngster Zeit hat sich das Symbol der Friedenstaube vom Kommunismus gelöst und wird in vielfältigen Kontexten genutzt.',
      'Hier ist eine erhobene geballte Faust als Zeichen für Solidarität, Stärke und Widerstand zu sehen.',
      'Außerdem sind Bücher abgebildet, die das Recht auf (Meinungs-)Bildung und Pressefreiheit symbolisieren.',
      '„Rette ihr Leben“ - Die chilenische Diktatur hinterlässt eine traurige Menschenrechtsbilanz: 2095 Ermordete oder Hingerichtete, 1102 spurlos Verschwundene, circa 250000 Exilierte.',
      'Der Auftraggeber dieses Plakates ist die World Federation of Democratic Youth (WFDY). Der Weltbund der Demokratischen Jugend wurde 1945 gegründet.',
      'Mittlerweile gehören ihm 150 Mitgliedsorganisationen aus 109 Ländern an und somit werden 30 Millionen Jugendliche weltweit durch den Verband vertreten.',
      'Der Weltbund ist sozialistisch ausgerichtet und macht mit diesem Plakat auf die menschenunwürdigen Zustände innerhalb der chilenischen Diktatur unter Pinochet aufmerksam.',
    ],
  },
  solidarity2: {
    header: '',
    texts: [
      'Das Plakat ist ein Nachdruck eines chilenischen Wahlplakats. Das Original aus dem Jahr 1970 stammt von der Radikalen Partei.',
      'An der Stelle, an der hier „Solidarität mit dem chilenischen Volk. Wahlkampfplakat aus Chile 1973: Vereinte Front gegen die Agression – immer mit der Linken -“ steht, stand im Original „B-18 M. Leon Prado; Diputado“.',
      'Mit dem Originalplakat wurde also für den Abgeordneten M. Leon Prado geworben. Die Radikalen waren innerhalb der Unidad Popular auf Liste B vertreten – B-18 bezeichnete demnach den Platz des Abgeordneten.',
      'Dieses nachgedruckte Plakat wurde von den Jungsozialist:innen der SPD und der SJD – Die Falken in Auftrag gegeben.',
      'Es intendiert sich solidarisch mit dem chilenischen Volk zu zeigen, nach dem das Militär gegen die demokratisch gewählte sozialistische Partei unter dem Präsidenten Salvador Allende geputscht und seither eine Militärdiktatur etabliert hatte.',
      '„Einheit gegen die Aggression“ ruft dazu auf, sich als Volk zusammen zu tun und eine Einheit zu bilden, um der Aggression in Form der Militärdiktatur entgegen zu treten.',
      'Hier ist symbolisch das chilenische Volk dargestellt. An dieser Stelle wird die Diversität der Bevölkerung sowie die „Einheit des Volkes“ zum Ausdruck gebracht.',
      'Die Hand, die nach dem Volk greift, soll die Konterrevolution von rechts in Chile symbolisieren.',
      'Verdeutlicht wird dies durch Symbole wie das Hakenkreuz der Faschisten, dem Stern der Nationalpartei, dem Doppelkreuz der Christdemokraten, der Spinne der Terrororganisation „Vaterland und Freiheit“, dem Hahn der rechtsradikalen Partei „PIR“ (zu sehen auf dem Fingernagel) sowie den Sternen und Streifen der US-Flagge.',
      '„Siempre a la izquierda.“ bedeutet „Immer links.“. Zu sehen ist hier zudem das Zeichen der Unidad Popular.',
      'Die Unidad Popular, abgekürzt UP, wurde 1969 als ein Wahlbündnis von linken chilenischen Parteien beziehungsweise Gruppierungen gegründet.',
      'Im Jahr 1970 bekam Salvador Allende, Kandidat der Unidad Popular, bei den Präsidentschaftswahlen mit 36.3 % die meisten Stimmen. Kurz darauf wurde er vom Nationalkongress in einer Stichwahl zum chilenischen Präsidenten gewählt.',
    ],
  },
  solidarity3: {
    header: '',
    texts: [],
  },
  youth: {
    header: '',
    texts: [
      'An dieser Stelle ist das Falken-Logo zu sehen: Die sozialistische Jugend Deutschlands – Die Falken. Die Falken setzen sich für mehr Demokratie, soziale Gerechtigkeit, Selbstbestimmung und Frieden für alle ein.',
      'Die rote Fahne als Symbol bringt eine lange Geschichte mit sich. Sie begann im Jahr 1830, als Arbeiter:innen einer Tuchfabrik für bessere wirtschaftliche Bedingungen demonstrierten.',
      'Warum sie eine rote Fahne als Zeichen ihres Widerstandes wählten, ist unklar.',
      'Eine Vermutung ist, dass das Rot den oftmals blutigen Kampf, den die Arbeiter:innen für ihre Rechte und Freiheiten führten, symbolisierte.',
      'Auch beim Schlesischen Weberaufstand 1844 versammelten sich die Arbeiter:innen unter einer roten Fahne. Durch die Revolutionsjahre 1848/49 gewann die rote Fahne größere Popularität und die rote Farbe wurde zum Symbol der Arbeiterbewegung.',
      'Mit dem 1863 gegründeten Allgemeinen Deutschen Arbeiterverein (ADAV), der ebenfalls die Rote Fahne als Symbol wählte, wurde das Rot zur Farbe der Sozialdemokratie.',
      'In den Folgejahrzehnten wählten auch sozialistische und kommunistische Bewegungen die rote Fahne zu ihrem Symbol. In Deutschland haben daher sowohl die SPD als auch die Linke die Farbe Rot als prägende Parteifarbe.',
      'Auch Staaten, deren Gesellschaftsform der Kommunismus oder Sozialismus ist, haben häufig einen roten Grundton in ihrer Flagge.',
      'Die Parole „Dem Hass keine Chance“ soll ein Zeichen für Vielfalt, Offenheit und Toleranz setzen.',
      'Gleichzeitig ruft sie zum Widerstand gegen Hass, Gewalt und Rassismus auf.',
      'Solidarität bezeichnet ein Zusammengehörigkeitsgefühl von Individuen und Gruppen.',
      'Das Konzept der Solidarität erlebte sowohl innergesellschaftlich als auch auf internationaler Ebene in der zweiten Hälfte des 20. Jahrhunderts ihre Blütezeit.',
      'In der Arbeiterbewegung steht Solidarität für den Zusammenhalt der Arbeit:innen untereinander. Hiermit eng verbunden ist die internationale Solidarität, insbesondere die Beziehungen zwischen Industrie- und Entwicklungsländern.',
      'In den Jahren 1978 bis 1979 wurde in Nicaragua der Diktator Anastasio Somoza gestürzt und der linksorientierte Frente Sandinista de Liberación Nacional kam an die Macht.',
      'Mit der Nicaraguanischen Revolution ging eine gesellschaftliche Umwälzung sowie ab 1980 der Contra-Krieg einher.',
      'Die rechtsgerichteten Contras begannen mit der Unterstützung der US-Regierung einen Kampf gegen das linksgerichtete sandinistische Regime.',
      'Zu der Contra-Gruppierung gehörten Anhänger:innen Somozas, Teile der bürgerlichen Opposition, Landwirte, enttäuschte Sandinist:innen und Teile der indigenen Bevölkerung.',
      'Die US-Regierung führte durch ihre finanzielle und logistische Unterstützung einen Stellvertreterkrieg gegen den Einfluss der Sowjetunion in Mittelamerika.',
      'Der Contra-Krieg dauerte bis 1990 an und forderte zahlreiche zivile Todesopfer.',
      'Mit dem Ende des Krieges wurde der politischen Gewalt jedoch kein Ende gesetzt. Bis in die zweite Hälfte der 1990 Jahre starben knapp 2000 weitere Menschen.',
      'Der Begriff „Ausländerfeindlichkeit“ bezeichnet eine negative Einstellung gegenüber Migrant:innen. Von Vorurteilen gestützt, werden diese ausgegrenzt und angefeindet.',
      'Der hier verwendete Begriff „AusländerFREUNDlichkeit“ soll das Gegenteil ausdrücken und dem Hass gegenüber Migrant:innen entgegenwirken.',
      'Die „Gelbe Hand“ ist ein Symbol für Toleranz und gegen Ausländerfeindlichkeit. Hinter dem Logo steht der Verein „Mach meinen Kumpel nicht an!“.',
      'Am 18.11.1986 wurde der Verein von dem Deutschen Gewerkschaftsbund und „ran“ in Düsseldorf gegründet und stellt somit eine der der ältesten antirassistischen Organisationen in Deutschland dar.',
      'Die „Gelbe Hand“ steht für das Engagement gegen Fremdenfeindlichkeit, Rassismus und Rechtsextremismus und spricht vor allem Jugendliche an.',
    ],
  },
  youth2: {
    header: 'BAFÖG Demo in Bonn',
    texts: ['Elefanten'],
  },
  youth3: {
    header: '',
    texts: [],
  },
}
