export const posterParadeItems = [
  {
    name: 'Arbeit & Bildung',
    caption:
      'Da für die Arbeiter:innen das Versprechen des Aufstiegs durch Bildung sowie gute Arbeitsbedingungen wichtige und identitätsprägende Themen waren, fanden sich diese auf viele Demoplakaten. BAFöG-Reform, die Aufhebung des Numerus Clausus, aber auch Lohnerhöhungen, gerechte Behandlung von Lehrlingen und gleichberechtigte Arbeitsbedingungen für Frauen gehörten dabei immer wieder zu den Forderungen.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/youth3.webp',
        href: 'youth3',
      },
      {
        image: '/posterParade/youth2.webp',
        href: 'youth2',
      },
    ],
  },
  {
    name: 'Frieden',
    caption:
      'Der Frieden nach dem Zweiten Weltkrieg fühlte sich durch die Teilung der Welt in politische Blöcke und den darauffolgenden Kalten Krieg fragil an. Linke Kritik fokussierte sich seit den 1950er Jahren insbesondere auf die Wiederbewaffnung in der BRD und später auf die NATO und die Stationierung von (Atom-)Waffen in Westeuropa. Einer der grundlegenden Gedanken dabei war, dass von Deutschland nie wieder Waffengewalt ausgehen sollte. In diesem Kontext ist u.a. das Plakat aus den 1950er Jahren zu sehen, dass gewaltsame Räumungen im Grenzstreifen zwischen DDR und BRD thematisiert.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/peace.webp',
        href: 'peace',
      },
      {
        image: '/posterParade/peace3.webp',
        href: 'peace3',
      },
    ],
  },
  {
    name: 'Partizipation',
    caption:
      'Partizipation ist ein sehr umfassender Begriff, der hier insbesondere für das Eintreten für die eigenen Bedürfnisse und Forderungen steht. Themen, wie der Aufruf zur Wahl bestimmter Parteiprogramme (meist der SPD), die Schaffung selbstorganisierter Jugendeinrichtungen oder auch das Engagement gegen Hass und Rassismus können darunter verstanden werden und waren immer wieder Demonstrationsanlässe.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/youth.webp',
        href: 'youth',
      },
      {
        image: '/posterParade/democracy.webp',
        href: 'democracy',
      },
    ],
  },
  {
    name: 'Internationale Solidarität',
    caption:
      'Linke Protestbewegungen (darunter auch jene, die von Arbeiter:innen angeführt wurden) unterstützten in vielen außereuropäischen Ländern emanzipatorische Bewegungen und demokratische Entwicklungen. Chile war dabei ein Beispiel, bei dem sich die Solidarität auch aus einer Kritik an den Einmischungen der USA entzündete. Ein anderes Beispiel ist die Unterstützung Nelson Mandelas und den Kampf gegen das südafrikanische Apartheidsregime.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/solidarity.webp',
        href: 'solidarity',
      },
      {
        image: '/posterParade/solidarity2.webp',
        href: 'solidarity2',
      },
    ],
  },
  {
    name: 'Antifaschismus',
    caption:
      'Seit den Anfängen der Bundesrepublik Deutschland nach dem Zweiten Weltkrieg war der Kampf gegen den Faschismus ein wichtiges Thema linker Arbeiter:innenjugendproteste. Die Tatsache, dass viele ehemalige NSDAP-Angehörige nach 1949 wichtige Positionen des Staates begleiteten, befeuerte immer wieder die öffentliche Debatte. Auch das Gedenken an nationalsozialistische Verbrechen gehöre und gehört zu den Kernthemen u.a. der Falken.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/antifascism2.webp',
        href: 'antifascism2',
      },
      {
        image: '/posterParade/antifascism.webp',
        href: 'antifascism',
      },
    ],
  },
  {
    name: 'Umwelt',
    caption:
      'Das Thema Umwelt spielte in linken Arbeiter:innenjugendprotesten der Nachkriegszeit eine eher untergeordnete Rolle und trat expliziter erst in den 1980er Jahren hervor. Insbesondere im Kontext mit Atomenergie werden die Themen Umwelt und Frieden aber auch verknüpft, denn die Gefahr, die von Atomwaffen ausgeht, wurde nicht nur als Bedrohung für den Menschen, sondern auch für seine Umwelt betrachtet. Die staatlich propagierte Differenzierung zwischen ziviler und militärischer Nutzung von Atomenergie wurde dabei immer seltener von Seiten linker Proteste übernommen.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/peace2.webp',
        href: 'peace2',
      },
      {
        image: '/posterParade/environment.webp',
        href: 'environment',
      },
    ],
  },
]

export const posterParadeTexts = {
  antifascism: {
    header: 'Der Schoß ist fruchtbar noch...',
    texts: [
      'Die Zeile „Der Schoß ist fruchtbar noch…“ stammt aus dem Theaterstück »Der aufhaltsame Aufstieg des Arturo Ui« von Bertolt Brecht. Darin geht es parabelhaft um den Aufstieg Adolf Hitlers.',
      'Der Epilog des Stückes endet mit den Worten: „So was hätt einmal fast die Welt regiert! Die Völker wurden seiner Herr, jedoch dass keiner uns zu früh da triumphiert - Der Schoß ist fruchtbar noch, aus dem das kroch!“',
      'Der Halbsatz „Nie wieder!“ gilt als ein Willy Brandt zugeschriebenes Zitat, welches fordert, dass von deutschem Boden nie wieder Krieg ausgehen dürfe.',
      '„Nie wieder!“ gilt im allgemeinen Sprachgebrauch aber auch generell für die Forderung, dass sich etwas wie der Holocaust und der Zweite Weltkrieg nicht wiederholen dürfen.',
      'Das Foto zeigt exemplarisch die Verbrechen der deutschen Nationalsozialisten anhand von Menschenleichen, die durch die Alliierten nach Kriegsende im Konzentrationslager Bergen-Belsen aufgefunden worden waren.',
      'Solche Bilder symbolisierten oft das unmenschliche Leid, das Menschen durch die Hand anderer Menschen aufgrund ihrer Herkunft, ihres Glaubens, ihrer Sexualität usw. angetan wurde.',
      'Dieses Bild symbolisiert also die Opfer nationalsozialistischer Herrschaft.',
      'Ergänzend zeigt das nebenstehende Foto die symbolisch die Täter nationalsozialistischer Herrschaft:',
      'Ein Angehöriger der Leibstandarte Adolf Hitler, der eine Trompete, vermutlich anlässlich eines Aufmarsches oder Appells spielt.',
      'Dieser paramilitärische Verband spielte eine relevante Rolle bei der Niederschlagung des Röhm-Putsches und den damit verbundenen Tötungen von SA-Mitgliedern.',
      'Der rote Blitz markiert symbolisch das Ende des Zweiten Weltkrieges und des Faschismus in Deutschland.',
      'Er erinnert durch seine rote Farbgebung aber auch an die spezielle Rolle, die der Sowjet-Kommunismus in der Gestalt von Stalin und Roten Armee dabei gespielt hat.',
      'In der unteren Bildreihe sieht man Fotografien aus der Zeit nach dem Zweiten Weltkrieg.',
      'Das erste Foto zeigt eine Gruppe von Neonazis mit Hakenkreuz, dem Symbol des deutschen Nationalsozialismus, im Hintergrund.',
      'Alle zeigen den Hitlergruß.',
      'In dem Bild sieht man einen trommelnden Jungen vor Fahnen mit dem Othala-Symbol.',
      'Othala ist die germanische Rune und bedeutet wahrscheinlich Erbbesitz, Heimat.',
      'In abgewandelter Form wurde dieses Symbol sowohl von der 7. SS-Freiwilligen-Gebirgs-Division „Prinz Eugen“, der Hitler-Jugend (HJ) und dem Rasse- und Siedlungshauptamt als Kennzeichen genutzt.',
      'Nach 1945 nutzen ebenfalls verschiedene nationalistische und neonazistische Verbände dieses Symbol in diversen Erscheinungsformen.',
      'Das Plakat stammt vom sozialistischen Jugendverband „SJD - Die Falken“.',
      'Dabei steht „SJD“ für Sozialistische Jugend Deutschlands.',
      'Dieser der SPD-nahestehende Verband trat seit den 1920er Jahren gegen Faschismus, Nationalismus und Krieg ein.',
    ],
  },
  antifascism2: {
    header: 'Nie wieder',
    texts: [
      'Das Erscheinungsbild der deutschen Soldaten im Zweiten Weltkrieg wurde vor allem durch die Marschstiefel geprägt.',
      'In der nationalsozialistischen Propaganda wurde eine permanente Assoziation zwischen den Stiefeln, dem Marschieren und den Paraden geschaffen.',
      'Die Intention dieser Assoziation war es ein Bild zu erschaffen, das die marschierenden Soldaten mit der Idee der geografischen Erweiterung verknüpft.',
      'Demnach sind die Marschstiefel in diesem Kontext nicht bloß ein Kleidungsstück der Soldaten, sondern sind ein propagandiertes Symbol für die Eroberungspläne des nationalsozialistischen Regimes.',
      'An dieser Stelle sind mehrere Hände zu sehen, die den Stiefel, als Symbol für die nationalsozialistische Herrschaft, wegdrücken.',
      'Die erhobenen geballten Fäuste sind ein Symbol für Solidarität, Stärke und den Befreiungskampf. Im Laufe der Geschichte haben sich viele verschiedene soziale Bewegungen die erhobene Faust zu eigen gemacht.',
      'Der Begriff „Reichskristallnacht“ ist eine veraltete Bezeichnung für die Novemberpogrome, welche vor allem in der Nacht vom 9.11.1938 auf den 10.11.1938 und in den Folgetagen im Deutschen Reich und im annektierten Österreich stattfanden.',
      'Die verharmlosende und euphemistische Bezeichnung „Reichkristallnacht“ ist auf die vielen Fensterglasscherben der zerstörten Wohnungen und Geschäfte jüdischer Bürger:innen zurück zu führen, weswegen der Begriff als problematisch gilt und heute durch die Begriffe „Novemberpogrome“ oder „Reichspogromnacht“ ersetzt wurde.',
      'Die Aktionen waren von oben angeordnet und wurden kurz nach dem Bekanntwerden des Attentats auf Ernst vom Rath initiiert. Dieses Attentat nutzte das nationalsozialistische Regime als rechtfertigenden Anlass für die Zerstörung jüdischen Eigentums sowie für die körperliche Misshandlung und Ermordung jüdischer Mitmenschen.',
      'In diesem Zeitraum haben Schlägertrupps des nationalsozialistischen Regimes Synagogen, jüdische Geschäfte und Wohnungen zerstört und in Brand gesetzt.',
      'Jüdisch gelesene Menschen wurden körperlich misshandelt, ermordet und in Konzentrationslager deportiert. Die Novemberpogrome gelten als radikalisierter Wendepunkt von der Diskriminierung der jüdischen Bevölkerung ab 1933 hin zur systematischen Vertreibung und Ermordung derselben.',
      'Zum 30-jährigen Gedenken trägt das Plakat die Überschrift „Nie wieder Reichskristallnacht“ und lud zu einem Fackelzug und einer Kundgebung am Platz der ehemaligen Synagoge in Gelsenkirchen ein. Der ehemalige SPD-Bundestagsabgeordnete Klaus Thüsing hielt anlässlich dessen eine Rede.',
      'Es stellt sich die Frage: Ist in diesem Kontext ein Fackelzug angebracht oder doch eher problematisch?',
      'Die Herausgeberin des Plakates ist die Sozialistische Jugend Deutschlands – Die Falken – Unterbezirk Gelsenkirchen. Die Falken setzen sich für mehr Demokratie, soziale Gerechtigkeit, Selbstbestimmung und Frieden für alle ein.',
    ],
  },
  antirascism: {
    header: '',
    texts: [],
  },
  democracy: {
    header: '',
    texts: [],
  },
  environment: {
    header: 'Demo gegen THTR-Probelauf',
    texts: [
      'Die im Jahr 1986 geschehenen Störfälle im Thorium-Hoch-Temperatur-Reaktor (THTR) markierten einen Wendepunkt in der Geschichte des Widerstandes gegen den THTR.',
      'Insgesamt beteiligten sich bei dieser Demonstration rund 3000 Bürger:innen, die gegen das THTR demonstrierten. Der Großteil der Demonstrant:innen stammte aus Hamm, das überregionale Interesse hielt sich in Grenzen.',
      'Dennoch galt die Demonstration als ein großer Erfolg.',
      'Zu sehen ist eine „Bierhalle“, wie sie typisch fürs Ruhrgebiet ist. Die Aufschrift „Isenbeck“ lokalisiert abermals den Standort, da das Pils in Hamm und Umgebung eine lokale Premium-Marke ist.',
      'Das Plakat stammt von der Bürgerinitiative Umweltschutz e.V. und ruft zu einer Demonstration gegen das Atomkraftwerk in Hamm-Werries am 17.09.1986 auf.',
      'Einige Zeit zuvor kam es mit der Nuklearkatastrophe von Tschernobyl am 26.04.1986 zur größten nuklearen Havarie des 20. Jahrhunderts.',
      'Kurz darauf, am 04.05.1986, drang aus dem Reaktor in Hamm radioaktiver Grafitstaub in die Umgebungsluft. Dieser Vorfall wäre meldepflichtig gewesen, wurde allerdings nicht gemeldet, in der Hoffnung man könne diesen Vorfall verschweigen.',
      'Wie viel strahlendes Material ausgetreten ist, lässt sich nicht nachvollziehen, da zu diesem Zeitpunkt das Messinstrument abgeschaltet war.',
      'Nebenbei bemerkt: Fällt den aufmerksamen Leser:innen dieses Plakates der Druckfehler in "Demonstration" auf?',
      'Grafisch dargestellt ist hier der Thorium-Hoch-Temperatur-Reaktor, kurz THTR-300, im nordrhein-westfälischen Hamm/Uentrop, aus dessen Wolke ein Totenkopf emporsteigt.',
      'Die Bauarbeiten am Kernkraftwerk THTR-300 begannen 1970 und wurden 1985 beendet. Anstelle von Brennstäben wurden in diesem Reaktor Graphitkugeln verwendet – damit wurde dem Prototypen AVR Jülich gefolgt, welcher 1967 in Betrieb ging.',
      'Bereits am AVR Jülich kam es 1978 zu einem Störfall. Im THTR häuften sich etliche nicht meldepflichtige und 21 meldepflichtige Vorfälle.',
      'Der dabei entstandene Kugelbruch beziehungsweise radioaktiver Grafitstaub befindet sich gegenwärtig immer noch in unbekannter Menge im Reaktor, erschwert den Rückbau des AKWs enorm und erhöht die Kosten.',
    ],
  },
  peace: {
    header: 'Bildanalyse Frieden',
    texts: ['Text 1', 'Text 2', 'Text 3', 'Text 4', 'Text 5', 'Text 6', 'Text 7', 'Text 8', 'Text 9'],
  },
  peace2: {
    header: 'Plakat 6 vor 12',
    texts: [
      'Am 21./22. November 1983 wurde im Deutschen Bundestag über die Stationierung von 108 Pershing II-Raketen und 96 Marschflugkörpern auf deutschem Territorium entschieden.',
      'Die Abgeordneten von CDU/CSU und FDP hatten angekündigt, mit einem JA für die Stationierung neuer Atomwaffen in der BRD zu stimmen, was sie schließlich auch taten.',
      'Der Countdown zeigt Sechs an: Herbert Werner (*20.3.1941) studierte nach dem Abitur Geschichte und Englisch an der Universität Tübingen und am University College of North Wales.',
      'Danach war er als Assessor, anschließend als Studienrat und später als Oberstudienrat am Humboldt-Gymnasium Ulm tätig.',
      'Im Jahr 1969 trat Werner in die CDU und in die Junge Union ein. In der 7. bis 12. Wahlperiode (1972–1994) vertrat er den Wahlkreis 173 bzw. 195 (Ulm) im Bundestag.',
      'Der Countdown zeigt Fünf an: Hermann Schwörer (*1.5.1922 – †24.11.017). Nachdem er im Jahr 1940 das Abitur bestand, begann er in Tübingen das Studium der Rechts- und Staatswissenschaften. Unterbrochen wurde das Studium durch Schwörers Einberufung in die Wehrmacht 1941.',
      '1945 setzte er das Studium fort. 1950 wurde er zum Dr. jur. promoviert und trat im selben Jahr in den familieneigenen Baustoffbetrieb ein. Im Jahr 1951 trat er der CDU bei und rückte 1958 für den verstorbenen Abgeordneten Herbert Wolff in den Bundestag nach.',
      'In der 5. bis 8. Wahlperiode (1965-1980) vertrat Schwörer den Wahlkreis 197 (Balingen), in der 9. bis12. Wahlperiode (1980-1994) den Wahlkreis 198 (Zollernalb-Sigmaringen). In der 3. Wahlperiode engagierte er sich unter anderem seit November 1958 im Ausschuss für Atomkernenergie und Wasserwirtschaft.',
      'Der Countdown zeigt Vier an: Manfred Abelein (*20.10.1930 – †17.1.2008) studierte nach dem Abitur Rechtswissenschaft, Volkswirtschaft und Politikwissenschaft und wurde im Jahr 1954 zum Dr. jur. an der Universität Basel promoviert.',
      'Als CDU-Abgeordneter des Wahlkreises 174 (Aalen-Heidenheim) gehörte er von 1965 bis 1990 dem Bundestag der 5. bis11. Wahlperiode an.',
      'Der Countdown zeigt Drei an: Elmar Kolb (*7.1.1936 – †13.5.2013). Er absolvierte eine kaufmännische Lehre und studierte von 1958 bis 1961 Maschinenbau am Ohm-Polytechnikum in Nürnberg. Im Jahr 1965 ist er der Jungen Union beigetreten und 1967 der CDU.',
      'Seit 1969 gehörte Kolb dem Bezirksvorstand der CDU, Süd-Württemberg-Hohenzollern, an. Im Jahr 1977 rückte er für den ausgeschiedenen Abgeordneten Norbert Nothhelfer in den Bundestag nach.',
      'Über die CDU-Landesliste Baden-Württemberg wurde er 1980 in den Bundestag gewählt und vertrat in der 10. und 11. Wahlperiode (1983–1990) den Wahlkreis 197 (Ravensburg – Bodensee) im Bundestag. Unter anderem gehörte er dem Ausschuss für Umwelt, Naturschutz und Reaktorsicherheit (seit Juni 1986) an.',
      'Der Countdown zeigt Zwei an: Hans-Peter Repnik (*27.5.1947) studierte nach dem Abitur und dem Wehrdienststudierte Rechts- und Staatswissenschaften an der Universität Freiburg.',
      'Nachdem er sich in den 1970er Jahren erst in der Jungen Union und später in der CDU engagierte, war er von 1989 bis 1994 Parlamentarischer Staatssekretär beim Bundesminister für wirtschaftliche Zusammenarbeit und Entwicklung.',
      'Zwischen 1980 und 2005 vertrat er den Wahlkreis 191 (Konstanz) im Bundestag. Repnik war von 2010 bis 2012 Mitglied und Vorsitzender des Rates für Nachhaltige Entwicklung.',
      'AUS: Der Atompilz von „Fat Man“ über Nagasaki am 9.8.1945 steht sinnbildlich für die US-amerikanischen Atombombenabwürfe auf Hiroshima und Nagasaki am 6.8.1945 und 9.8.1945.',
      'Insgesamt töteten die Atombombenexplosionen circa 100.000 Menschen. An den Folgeschäden starben allein bis Ende 1945 weitere 130.000 Menschen. In den Folgejahren stieg die Zahl der Opfer ins Exorbitante.',
      'Den Befehl zum Abwurf der Atombomben gab der amerikanische Präsident Harry S. Truman. Am 2.9.1945 endete der Zweite Weltkrieg mit der Kapitulation Japans auch in Asien.',
      'Trotz der Atombombenabwürfe auf Hiroshima und Nagasaki entstand durch propagandierte Trennung zwischen ziviler und militärischer Atomenergienutzung eine Gleichzeitigkeit von Atomeuphorie und Atomangst.',
      'Die metaphorische Weltuntergangsuhr beziehungsweise Atomkriegsuhr soll der Öffentlichkeit verdeutlichen, wie groß das Risiko einer globalen Katastrophe insbesondere im Hinblick auf einen Atomkrieg oder einer Klimakatastrophe ist.',
      'Die Politikerporträts auf dem Plakat tragen allesamt eine Zahl von 6 bis 2 im linken unteren Winkel. Diese Zahlen markieren das Herunterzählen von 6 bis 1.',
      'In dem mit 1 bezifferten Bild explodiert schließlich die Atombombe und der Countdown endet mit der „atomaren Katastrophe“.',
    ],
  },
  peace3: {
    header: 'Ostermarsch 1984',
    texts: [
      'Ganz schön viele verschiedene Menschen! Vom Kleinkind über Arbeiter*innen und Angestellte bis hin zu Rentner*innen sind diese illustrierten Menschen allen Alters und aller sozialen Schichten in einem vereint: in ihrem „Nein“ zum Rüstungswahn.',
      'Der Hintergrund dieser Demonstration ist die Zeit des NATO-Doppelbeschlusses aus dem Jahr 1979. In Westdeutschland kam es vermehrt zu Großdemonstrationen. Auch wenn oft jüngere Menschen die Mehrheit bei solchen Demonstrationen beziehungsweise Ostermärschen bildet, sind hier alle Altersklassen und Gesellschaftsschichten vertreten.',
      'Typisch für Friedensdemonstrationen sind die hier abgebildeten Fahnen, Transparente und Schilder mit der symbolischen Friedentaube oder beispielsweise kurzen Leitsprüchen wie „Nein zu Atom“.',
      'Der erste Ostermarsch in Deutschland fand im Jahr 1960 statt und führte als mehrtägiger Marsch von Hamburg über Bremen, Hannover und Braunschweig nach Bergen-Hohne.',
      'Bergen-Hohne war ein Raketenübungsgelände der Bundeswehr, wo, Berichten zufolge, eine Batterie Honest-John-Raketen mit atomaren Sprengköpfen stationiert worden war. Hieran nahmen circa 120 Teilnehmer*innen teil.',
      'Seitdem finden alljährlich rings um die Osterfeiertage bundesweit Ostermärsche statt, immer unter dem Motto: Für den Frieden und gegen Waffen.',
      'Insbesondere in den Jahren von 1979 bis 1990 kam es durch den NATO-Doppelbeschluss zu einem neuen Aufschwung der Ostermärsche.',
      '1984 nahmen so bundesweit circa 600.000 Menschen zum Abschluss der Ostermärsche an Kundgebungen für Abrüstung und Frieden teil.',
      'Die Pershing II war eine militärische Rakete aus US-amerikanischer Produktion, benannt nach dem US-General John Joseph Pershing. In Westdeutschland begann wenige Tage nach der Zustimmung des Deutschen Bundestag vom 22.11.1983 die Stationierung der Pershing II.',
      'Auf diesem Banner ist deutlich der Spruch „Stoppt den Rüstungswahn“ zu lesen. Dieser Leitspruch wurde und wird häufig bei pazifistischen und antimilitaristischen Demonstrationen und Ostermärschen genutzt. Im Jahr 1984 war die Situation aufgrund des NATO-Doppelbeschlusses und besonders besorgniserregend.',
      'Seit 1970 wurden die Raketen Pershing II und die Marschflugkörper Cruise Missiles entwickelt. Durch ihre Treffgenauigkeit und flexible Reichweite galten sie als technische Innovation.',
      'Im Dezember 1979 wurde von den Außen- und Verteidigungsministern der NATO-Mitgliedstaaten in Brüssel beschlossen, die Pershing II als auch die Cruise Missiles in Europa zu stationieren.',
      'Zeitgleich sollten der Sowjetunion aber Verhandlungen über eine beidseitige Reduzierung nuklearer Waffen angeboten werden.',
      'Diese Karikatur zeigt den ehemaligen deutschen Bundeskanzler Helmut Kohl (1930–2017), der von 1982 bis 1998 im Amt war. Kohl war nicht nur Gegenstand unzähliger Satiren, sondern auch von Karikaturen. Besonders oft wurde er als Birne karikiert, aber die Kopfform erinnerte auch an ein Ei.',
      'Und so wurde Kohl in diesem Plakat als „Eierkopf“ dargestellt –  eine umgangssprachliche Bezeichnung, die abwertend beziehungsweise ironisch für Intellektuelle genutzt wird.',
      'Ein Demonstrant tritt Helmut Kohl, dargestellt als „Eierkopf“, ins Gesicht, woraufhin seine ‚Schale‘ reißt. Dieser Akt der Gewalt gegen den (karikierten) Bundeskanzler symbolisiert die Wut und den Widerstand der Bevölkerung gegen die politischen Entscheidungen.',
      'Häufig sind auch ganz konkrete Aufforderungen und Informationen Teil eines Plakats. Denn: Woher sollten die Aktivist*innen ganz ohne Internet wissen, wann und wo es mit der Demo losgeht und welches Programm sie erwartet?',
      'Und so wird an dieser Stelle über den Ablauf des Ostermarsches informiert: Angefangen mit einer Blockade der US-Kaserne in der Garlstedter Heide vor Ostern war für den Ostersonntag ein Ostermarsch von Neuengamme (Standort eines ehemaligen Konzentrationslagers) nach Hamburg geplant.',
      'Aus allen Hamburger Stadtteilen sollten dann die Demonstrant*innen aus allen Himmelsrichtungen in Sternmärschen zum Rathausmarkt kommen. Dort fand dann die Abschlusskundgebung statt. Mit Unterstützung der Hamburger Stadtteilinitiativen war dann zwischen dem 24. und 28.8.1984 noch eine Aktionswoche betrieblicher Friedensinitiativen geplant – so konnte man sich auch gut einstimmen auf den schon bald folgenden Arbeiterkampftag am 1. Mai.',
      'Das Plakat stammt von den Jungsozialisten der SPD. Sie positionierten sich in den 1980er Jahren explizit gegen die Stationierung von Atomwaffen und gegen eine Politik der Aufrüstung. Von den Jusos gingen deshalb verschiedenste Aktionen aus, so etwa der Aufruf zum Ostermarsch in Hamburg wie hier.',
      'Die Friedensbewegung der 1980er Jahren brachte bis heute die größten Friedensdemos für Pazifismus und Antimilitarismus in der bundesdeutschen Geschichte mit sich.',
    ],
  },
  solidarity: {
    header: 'Save their lives',
    texts: [
      '„Freiheit für alle politischen Gefangenen in Chile!“ - Nach dem Putsch am 11.09.1973 gegen den gewählten Präsidenten Salvador Allende begann unter Augusto Pinochet eine brutale Diktatur.',
      'Das Militär hatte binnen kürzester Zeit das Land unter seine Kontrolle gebracht. Mehr als 27.000 (vermeintlich) Regimegegner:innen wurden verfolgt, gefangen genommen und gefoltert.',
      'An dieser Stelle ist eine „Friedenstaube“ abgebildet. Ursprünglich geht das Symbol der Friedenstaube auf die Geschichte Noahs im Alten Testament zurück. Im Zentrum dieses Plakates steht allerdings die grafische Form der Friedenstaube, die auf Pablo Picassos Werk basiert.',
      'Picasso, engagiertes Mitglied der kommunistischen Partei, gestaltete mit der Friedenstaube Plakate in Wrocław, Paris, Stockholm, Sheffield und Rom. Während des Kalten Krieges wurde die Friedenstaube auf diesem Weg zum wichtigsten Hoffnungssymbol.',
      'Er unterstützte mit verschiedenen Varianten dieses Motivs die kommunistische Partei in Frankreich, anderen Ländern und radikalen Organisationen in Westeuropa.',
      'Mit seinen Arbeiten drückte Picasso seine eigene politische Haltung künstlerisch aus, propagierte für die Friedensbewegung und protestierte gegen Krieg und Unterdrückung.',
      'In jüngster Zeit hat sich das Symbol der Friedenstaube vom Kommunismus gelöst und wird in vielfältigen Kontexten genutzt.',
      'Hier sind mehrere erhobene Fäuste als Zeichen für Solidarität, Stärke und Widerstand dargestellt.',
      'Außerdem sind Bücher abgebildet, die das Recht auf (Meinungs-)Bildung und Pressefreiheit symbolisieren.',
      '„Rettet ihre Leben“ - Die chilenische Diktatur hinterlässt eine traurige Menschenrechtsbilanz: 2095 Ermordete oder Hingerichtete, 1102 spurlos Verschwundene, circa 250000 Exilierte.',
      'Der Auftraggeber dieses Plakates ist die World Federation of Democratic Youth (WFDY). Der Weltbund der Demokratischen Jugend wurde 1945 gegründet.',
      'Mittlerweile gehören ihm 150 Mitgliedsorganisationen aus 109 Ländern an und somit werden 30 Millionen Jugendliche weltweit durch den Verband vertreten.',
      'Der Weltbund ist sozialistisch ausgerichtet und macht mit diesem Plakat auf die menschenunwürdigen Zustände innerhalb der chilenischen Diktatur unter Pinochet aufmerksam.',
    ],
  },
  solidarity2: {
    header: 'Solidarität mit dem chilenischen Volk',
    texts: [
      'Das Plakat ist ein Nachdruck eines chilenischen Wahlplakats. Das Original aus dem Jahr 1970 stammt von der Radikalen Partei.',
      'An der Stelle, an der hier „Solidarität mit dem chilenischen Volk. Wahlkampfplakat aus Chile 1973: Vereinte Front gegen die Agression – immer mit der Linken -“ steht, stand im Original „B-18 M. Leon Prado; Diputado“.',
      'Mit dem Originalplakat wurde also für den Abgeordneten M. Leon Prado geworben. Die Radikalen waren innerhalb der Unidad Popular auf Liste B vertreten – B-18 bezeichnete demnach den Platz des Abgeordneten.',
      'Dieses nachgedruckte Plakat wurde von den Jungsozialist:innen der SPD und der SJD – Die Falken in Auftrag gegeben.',
      'Es intendiert sich solidarisch mit dem chilenischen Volk zu zeigen, nach dem das Militär gegen die demokratisch gewählte sozialistische Partei unter dem Präsidenten Salvador Allende geputscht und seither eine Militärdiktatur etabliert hatte.',
      '„Einheit gegen die Aggression“ ruft dazu auf, sich als Volk zusammen zu tun und eine Einheit zu bilden, um der Aggression in Form der Militärdiktatur entgegen zu treten.',
      'Hier ist symbolisch das chilenische Volk dargestellt. An dieser Stelle wird die Diversität der Bevölkerung sowie die „Einheit des Volkes“ zum Ausdruck gebracht.',
      'Die Hand, die nach dem Volk greift, soll die Konterrevolution von rechts in Chile symbolisieren.',
      'Verdeutlicht wird dies durch Symbole wie das Hakenkreuz der Faschisten, dem Stern der Nationalpartei, dem Doppelkreuz der Christdemokraten, der Spinne der Terrororganisation „Vaterland und Freiheit“, dem Hahn der rechtsradikalen Partei „PIR“ (zu sehen auf dem Fingernagel) sowie den Sternen und Streifen der US-Flagge.',
      '„Siempre a la izquierda.“ bedeutet „Immer links.“. Zu sehen ist hier zudem das Zeichen der Unidad Popular.',
      'Die Unidad Popular, abgekürzt UP, wurde 1969 als ein Wahlbündnis von linken chilenischen Parteien beziehungsweise Gruppierungen gegründet.',
      'Im Jahr 1970 bekam Salvador Allende, Kandidat der Unidad Popular, bei den Präsidentschaftswahlen mit 36.3 % die meisten Stimmen. Kurz darauf wurde er vom Nationalkongress in einer Stichwahl zum chilenischen Präsidenten gewählt.',
    ],
  },
  solidarity3: {
    header: '',
    texts: [],
  },
  youth: {
    header: 'Jugend für Ausländerfreundlichkeit',
    texts: [
      'An dieser Stelle ist das Falken-Logo zu sehen: Die sozialistische Jugend Deutschlands – Die Falken. Die Falken setzen sich für mehr Demokratie, soziale Gerechtigkeit, Selbstbestimmung und Frieden für alle ein.',
      'Die rote Fahne als Symbol bringt eine lange Geschichte mit sich. Sie begann im Jahr 1830, als Arbeiter:innen einer Tuchfabrik für bessere wirtschaftliche Bedingungen demonstrierten.',
      'Warum sie eine rote Fahne als Zeichen ihres Widerstandes wählten, ist unklar. Eine Vermutung ist, dass das Rot den oftmals blutigen Kampf, den die Arbeiter:innen für ihre Rechte und Freiheiten führten, symbolisierte.',
      'Auch beim Schlesischen Weberaufstand 1844 versammelten sich die Arbeiter:innen unter einer roten Fahne. Durch die Revolutionsjahre 1848/49 gewann die rote Fahne größere Popularität und die rote Farbe wurde zum Symbol der Arbeiterbewegung.',
      'Mit dem 1863 gegründeten Allgemeinen Deutschen Arbeiterverein (ADAV), der ebenfalls die Rote Fahne als Symbol wählte, wurde das Rot zur Farbe der Sozialdemokratie.',
      'In den Folgejahrzehnten wählten auch sozialistische und kommunistische Bewegungen die rote Fahne zu ihrem Symbol. In Deutschland haben daher sowohl die SPD als auch die Linke die Farbe Rot als prägende Parteifarbe.',
      'Auch Staaten, deren Gesellschaftsform der Kommunismus oder Sozialismus ist, haben häufig einen roten Grundton in ihrer Flagge.',
      'Die Parole „Dem Hass keine Chance“ soll ein Zeichen für Vielfalt, Offenheit und Toleranz setzen. Gleichzeitig ruft sie zum Widerstand gegen Hass, Gewalt und Rassismus auf.',
      'Solidarität bezeichnet ein Zusammengehörigkeitsgefühl von Individuen und Gruppen. Das Konzept der Solidarität erlebte sowohl innergesellschaftlich als auch auf internationaler Ebene in der zweiten Hälfte des 20. Jahrhunderts ihre Blütezeit.',
      'In der Arbeiterbewegung steht Solidarität für den Zusammenhalt der Arbeit:innen untereinander. Hiermit eng verbunden ist die internationale Solidarität, insbesondere die Beziehungen zwischen Industrie- und Entwicklungsländern.',
      'In den Jahren 1978 bis 1979 wurde in Nicaragua der Diktator Anastasio Somoza gestürzt und der linksorientierte Frente Sandinista de Liberación Nacional kam an die Macht. Mit der Nicaraguanischen Revolution ging eine gesellschaftliche Umwälzung sowie ab 1980 der Contra-Krieg einher.',
      'Die rechtsgerichteten Contras begannen mit der Unterstützung der US-Regierung einen Kampf gegen das linksgerichtete sandinistische Regime. Zu der Contra-Gruppierung gehörten Anhänger:innen Somozas, Teile der bürgerlichen Opposition, Landwirte, enttäuschte Sandinist:innen und Teile der indigenen Bevölkerung.',
      'Die US-Regierung führte durch ihre finanzielle und logistische Unterstützung einen Stellvertreterkrieg gegen den Einfluss der Sowjetunion in Mittelamerika.',
      'Der Contra-Krieg dauerte bis 1990 an und forderte zahlreiche zivile Todesopfer. Mit dem Ende des Krieges wurde der politischen Gewalt jedoch kein Ende gesetzt. Bis in die zweite Hälfte der 1990 Jahre starben knapp 2000 weitere Menschen.',
      'Der Begriff „Ausländerfeindlichkeit“ bezeichnet eine negative Einstellung gegenüber Migrant:innen. Von Vorurteilen gestützt, werden diese ausgegrenzt und angefeindet.',
      'Der hier verwendete Begriff „AusländerFREUNDlichkeit“ soll das Gegenteil ausdrücken und dem Hass gegenüber Migrant:innen entgegenwirken.',
      'Die „Gelbe Hand“ ist ein Symbol für Toleranz und gegen Ausländerfeindlichkeit. Hinter dem Logo steht der Verein „Mach meinen Kumpel nicht an!“.',
      'Am 18.11.1986 wurde der Verein von dem Deutschen Gewerkschaftsbund und „ran“ in Düsseldorf gegründet und stellt somit eine der der ältesten antirassistischen Organisationen in Deutschland dar.',
      'Die „Gelbe Hand“ steht für das Engagement gegen Fremdenfeindlichkeit, Rassismus und Rechtsextremismus und spricht vor allem Jugendliche an.',
    ],
  },
  youth2: {
    header: 'BAFÖG Demo in Bonn',
    texts: ['Elefanten'],
  },
  youth3: {
    header: '',
    texts: [],
  },
}
