export const posterParadeItems = [
  {
    name: 'Arbeit & Bildung',
    caption:
      'Da für die Arbeiter:innen das Versprechen des Aufstiegs durch Bildung sowie gute Arbeitsbedingungen wichtige und identitätsprägende Themen waren, fanden sich diese auf viele Demoplakaten. BAFöG-Reform, die Aufhebung des Numerus Clausus, aber auch Lohnerhöhungen, gerechte Behandlung von Lehrlingen und gleichberechtigte Arbeitsbedingungen für Frauen gehörten dabei immer wieder zu den Forderungen.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/youth3.webp',
        href: 'youth3',
      },
      {
        image: '/posterParade/youth2.webp',
        href: 'youth2',
      },
    ],
  },
  {
    name: 'Frieden',
    caption:
      'Der Frieden nach dem Zweiten Weltkrieg fühlte sich durch die Teilung der Welt in politische Blöcke und den darauffolgenden Kalten Krieg fragil an. Linke Kritik fokussierte sich seit den 1950er Jahren insbesondere auf die Wiederbewaffnung in der BRD und später auf die NATO und die Stationierung von (Atom-)Waffen in Westeuropa. Einer der grundlegenden Gedanken dabei war, dass von Deutschland nie wieder Waffengewalt ausgehen sollte. In diesem Kontext ist u.a. das Plakat aus den 1950er Jahren zu sehen, dass gewaltsame Räumungen im Grenzstreifen zwischen DDR und BRD thematisiert.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/peace.webp',
        href: 'peace',
      },
      {
        image: '/posterParade/peace3.webp',
        href: 'peace3',
      },
    ],
  },
  {
    name: 'Partizipation',
    caption:
      'Partizipation ist ein sehr umfassender Begriff, der hier insbesondere für das Eintreten für die eigenen Bedürfnisse und Forderungen steht. Themen, wie der Aufruf zur Wahl bestimmter Parteiprogramme (meist der SPD), die Schaffung selbstorganisierter Jugendeinrichtungen oder auch das Engagement gegen Hass und Rassismus können darunter verstanden werden und waren immer wieder Demonstrationsanlässe.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/youth.webp',
        href: 'youth',
      },
      {
        image: '/posterParade/democracy.webp',
        href: 'democracy',
      },
    ],
  },
  {
    name: 'Internationale Solidarität',
    caption:
      'Linke Protestbewegungen (darunter auch jene, die von Arbeiter:innen angeführt wurden) unterstützten in vielen außereuropäischen Ländern emanzipatorische Bewegungen und demokratische Entwicklungen. Chile war dabei ein Beispiel, bei dem sich die Solidarität auch aus einer Kritik an den Einmischungen der USA entzündete. Ein anderes Beispiel ist die Unterstützung Nelson Mandelas und den Kampf gegen das südafrikanische Apartheidsregime.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/solidarity.webp',
        href: 'solidarity',
      },
      {
        image: '/posterParade/solidarity2.webp',
        href: 'solidarity2',
      },
    ],
  },
  {
    name: 'Antifaschismus',
    caption:
      'Seit den Anfängen der Bundesrepublik Deutschland nach dem Zweiten Weltkrieg war der Kampf gegen den Faschismus ein wichtiges Thema linker Arbeiter:innenjugendproteste. Die Tatsache, dass viele ehemalige NSDAP-Angehörige nach 1949 wichtige Positionen des Staates begleiteten, befeuerte immer wieder die öffentliche Debatte. Auch das Gedenken an nationalsozialistische Verbrechen gehöre und gehört zu den Kernthemen u.a. der Falken.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/antifascism2.webp',
        href: 'antifascism2',
      },
      {
        image: '/posterParade/antifascism.webp',
        href: 'antifascism',
      },
    ],
  },
  {
    name: 'Umwelt',
    caption:
      'Das Thema Umwelt spielte in linken Arbeiter:innenjugendprotesten der Nachkriegszeit eine eher untergeordnete Rolle und trat expliziter erst in den 1980er Jahren hervor. Insbesondere im Kontext mit Atomenergie werden die Themen Umwelt und Frieden aber auch verknüpft, denn die Gefahr, die von Atomwaffen ausgeht, wurde nicht nur als Bedrohung für den Menschen, sondern auch für seine Umwelt betrachtet. Die staatlich propagierte Differenzierung zwischen ziviler und militärischer Nutzung von Atomenergie wurde dabei immer seltener von Seiten linker Proteste übernommen.',
    contentPosition: 'middle',
    items: [
      {
        image: '/posterParade/peace2.webp',
        href: 'peace2',
      },
      {
        image: '/posterParade/environment.webp',
        href: 'environment',
      },
    ],
  },
]

export const posterParadeTexts = {
  antifascism: {
    header: 'Der Schoß ist fruchtbar noch...',
    texts: [
      'Die Zeile „Der Schoß ist fruchtbar noch…“ stammt aus der letzten Zeile des Theaterstücks „Der aufhaltsame Aufstieg des Arturo Ui“ von Bertolt Brecht. In der  1941 – mitten in der Zeit des Nationalsozialismus! – verfassten Parabel über den Aufstieg Adolf Hitlers geht es darum, sich zu engagieren und wachsam zu sein, nicht aufzugeben, sondern aufzuhalten, was aufzuhalten ist.',
      'Die lehrreichen Worte am Ende des Theaterstücks lauten: „Ihr aber lernet, wie man sieht, statt stiert/ Und handelt, statt zu reden noch und noch./ So was hätt einmal fast die Welt regiert!/ Die Völker wurden seiner Herr, jedoch/ Dass keiner uns zu früh da triumphiert –/ Der Schoß ist fruchtbar noch, aus dem das kroch.“',
      'Der Ausruf „Nie wieder!“ wird Willy Brandt zugeschrieben. Damit war im Speziellen gemeint, dass von deutschem Boden nie wieder Krieg ausgehen dürfe.',
      'Im heutigen Sprachgebrauch wird die Forderung eines „Nie wieder!“ allgemeiner verwendet: Shoah und Weltkrieg dürfen sich keinesfalls wiederholen.',
      'Das Foto steht stellvertretend für die unfassbaren Verbrechen des nationalsozialistischen Regimes.',
      'Die Alliierten fanden bei der Befreiung  der Konzentrations- und Vernichtungslager 1945 solche Leichenberge und Massengräber vor und dokumentierten das Unrecht in Fotografien und Filmen.',
      'Die Bilder symbolisieren das unmenschliche Leid, dass Menschen durch andere Menschen aufgrund ihrer Herkunft, ihres Glaubens, ihrer politischen Meinung, ihrer Sexualität usw. angetan wurde.',
      'Ergänzend zeigt das nebenstehende Foto einen trompetenden Angehörigen der Adolf-Hitler-Standarte – der Leibstandarte Hitlers.',
      'Nicht zu übersehen ist der Totenkopf auf dem Trompetenwimpel, das Emblem der SS-Totenkopfverbände.',
      'Diese waren insbesondere verantwortlich für die Verbrechen in den nationalsozialistischen Konzentrations- und Vernichtungslagern. Heute ist das Symbol verboten.',
      'Der rote Blitz markiert symbolisch das Ende des Zweiten Weltkrieges und des Faschismus.',
      'Er erinnert aber auch an die spezielle Rolle, die der Kommunismus in der Gestalt von Stalin und der Sowjetunion dabei spielt.',
      'Nach 1945 wirkten die personellen und ideellen Hinterlassenschaften des Nationalsozialismus weiter.',
      'Ehemalige Nationalsozialist*innen trafen sich ebenso wie sich neue neonazistische Gruppierungen gründeten.',
      'Auf dem Foto zu sehen ist eine Gruppe, die sich in den 1950er Jahren traf und nicht nur unverhohlen das verbotene Hakenkreuzsymbol des Nationalsozialismus, sondern auch den ebenso verbotenen Hitler-Gruß zeigten.',
      'Der trommelnde Junge steht vor Fahnen mit dem Othala-Symbol.',
      'Othala ist eine germanische Rune und soll für Erbbesitz und Heimat stehen.',
      'In abgewandelter Form wurde dieses Symbol sowohl von der 7. SS-Freiwilligen-Gebirgs-Division „Prinz Eugen“, der Hitler-Jugend (HJ) und dem Rasse- und Siedlungshauptamt als Kennzeichen genutzt.',
      'Nach 1945 wurde das Othala-Symbol in (neo)nazistischen Gruppierungen verwendet.',
      'Das Plakat stammt vom Jugendverband der Sozialistischen Jugend Deutschlands – Die Falken.',
      'Die Falken gründeten sich nach 1945 in Tradition der sozialdemokratischen Reichsarbeitsgemeinschaft der Kinderfreunde und der Sozialistischen Arbeiter-Jugend.',
      'Als linker Jugendverband nimmt die antifaschistische und Gedenkarbeit eine besondere Funktion ein.',
    ],
  },
  antifascism2: {
    header: 'Nie wieder',
    texts: [
      'Es sind drei Hände zu sehen, die den Marschstiefel – als Symbol für die nationalsozialistische Herrschaft – mit aller Gewalt wegdrücken. Die zwei zusätzlichen geballten Fäuste sind ein Symbol für Solidarität und Stärke. Im Laufe der Geschichte haben sich viele verschiedene soziale Bewegungen die erhobene Faust zu eigen gemacht.',
      'Die Marschstiefel stehen symbolisch für die Wehrmachtssoldaten im Zweiten Weltkrieg. In der nationalsozialistischen Propaganda wurde eine permanente Verbindung zwischen den Stiefeln, dem Marschieren und den Paraden als Zeichen der militärischen Macht des Regimes geschaffen.',
      'Damit verknüpft war die imperialistische Idee der geografischen Erweiterung des Deutschen Reiches v. a. in Richtung Osteuropa.',
      'Die Marschstiefel sind in diesem Kontext also nicht bloß ein Teil der Uniform von Soldaten, sondern ein Symbol für die Eroberungspläne des nationalsozialistischen Regimes.',
      'Der Begriff „Reichskristallnacht“ ist eine veraltete Bezeichnung für die nationalsozialistischen Angriffe auf Synagogen und jüdische Mitmenschen, die vor allem in der Nacht vom 9. auf den 10.11.1938 und in den Folgetagen deutschlandweit und in Österreich stattfanden.',
      'Die verharmlosende und euphemistische Bezeichnung „Reichkristallnacht“ hat keine gänzlich geklärte Herkunft. „Reichs-“ bezieht sich vermutlich auf die reichsweiten Pogrome, „-Kristallnacht“ ist auf die vielen Glasscherben der zerstörten Wohnräume und Synagogen zurückzuführen.',
      'Deswegen gilt der Begriff als problematisch und wurde in jüngster Zeit durch „Novemberpogrome“ oder „Reichspogromnacht“ ersetzt.',
      'Das nationalsozialistische Regime nutzte ein Attentat auf den Diplomaten und Botschaftssekretär Ernst vom Rath (1909–1938) als Rechtfertigung für die Novemberprogrome. Schlägertrupps des nationalsozialistischen Regimes zerstörten Synagogen, jüdische Geschäfte und jüdischen Wohnraum und setzten diese in Brand.',
      'Jüdische Mitmenschen wurden körperlich misshandelt, ermordet und in Konzentrationslager deportiert. Die Novemberpogrome gelten als radikaler Wendepunkt von der Diskriminierung der Juden ab 1933 hin zur systematischen Ermordung der Juden in der Shoah.',
      'Zum 40-jährigen Gedenken trug das Plakat die Überschrift „Nie wieder Reichskristallnacht“ und lud zu einem Fackelzug und einer Kundgebung am Platz der ehemaligen Synagoge in Gelsenkirchen ein.',
      'Der ehemalige SPD-Bundestagsabgeordnete Klaus Thüsing hielt anlässlich dessen eine Rede.',
      'Es stellt sich die Frage: Ist in diesem Kontext ein Fackelzug angebracht oder doch eher problematisch – waren doch Fackelzüge auch ein propagandistisches Element des nationalsozialistischen Regimes?',
      'An dieser Stelle ist die Auftraggeberin des Plakates und Initiatorin der Gedenkveranstaltung zu lesen: die Sozialistische Jugend Deutschlands – Die Falken aus dem Unterbezirk Gelsenkirchen.',
      'Die Falken setzen sich bis heute für mehr Demokratie, soziale Gerechtigkeit, Selbstbestimmung und Frieden für alle ein.',
    ],
    sources: [
      {
        text: 'LeMO: Der Zweite Weltkrieg - Kriegsverlauf - Marschstiefel',
        link: 'https://www.dhm.de/lemo/kapitel/der-zweite-weltkrieg/kriegsverlauf/marschstiefel.html',
      },
      {
        text: 'Reichspogromnacht - 9. November 1938',
        link: 'https://www.lpb-bw.de/reichspogromnacht',
      },
      {
        text: 'SJD - Die Falken Unterbezirk Gelsenkirchen',
        link: 'https://www.falken-gelsenkirchen.de/wirfalken',
      },
    ],
  },
  democracy: {
    header: 'Diese Freiheit nicht!',
    texts: [
      'Im Fokus dieses Plakats steht die Karikatur von Franz Josef Strauß (1915-1988). Strauß war ein CSU-Politiker, der jahrzehntelang großen Einfluss auf die bundesrepublikanische Politik hatte.',
      'Ab 1949 war er Abgeordneter im Bundestag, 1955 wurde er Atomminister und 1956 Verteidigungsminister. Während er in dieser Position war, kam es 1962 zur sogenannten „Spiegel-Affäre“.',
      'Im Jahr 1966 wurde Strauß in der Großen Koalition Finanzminister. In der Bundestagswahl 1980 trat er als Kanzlerkandidat der CDU/CSU gegen Helmut Schmidt von der SPD an, verlor jedoch.',
      'Von 1978 bis zu seinem Tod im Jahr 1988 war er Ministerpräsident von Bayern. Die Person und der Stil von Franz Josef Strauß zogen auf der einen Seite das konservative, nationalliberale-bürgerliche Lager an.',
      'Auf der anderen Seite wurde er im linken Spektrum als Wortführer eines antisozialistischen, staatlichen Ordnungsdenkens wahrgenommen und zum Antagonisten stilisiert.',
      'Doch auch innerhalb der CDU/CSU war Strauß umstritten, worunter die Einheit der Union wiederholte Male litt. Ein Höhepunkt der Spaltung von CSU und CSU war die Zeit nach der Wahlniederlage von 1976, für die Strauß die CDU und ihr „zögerliches Verhalten“ verantwortlich machte.',
      'Daraufhin verkündete er die Auflösung der CDU/CSU-Fraktionsgemeinschaft im Bundestag. Als die CDU damit drohte einen eigenen Landesverband in Bayern zu gründen, lenkte Strauß im Dezember 1976 ein.',
      'Franz Josef Strauß hält eine Geißel in der Hand, also einen Stab, an dessen Ende schmale Lederriemen befestigt sind und der als Peitsche verwendet wird.',
      'An der Geißel hängen die Porträts verschiedener Politiker',
      'Der FDP-Politiker Hans Friderichs (geb. 1931) war in den Jahren von 1960 bis 1964 Mitglied des Kreistages Bingen und Vorsitzender der FDP-Fraktion ebenda, von 1965 bis 1969 war er Mitglied des Deutschen Bundestages.',
      'Im Jahr 1969 wurde er zum Staatssekretär im Ministerium für Landwirtschaft, Weinbau und Forsten des Landes Rheinland-Pfalz ernannt. Von 1972 bis 1977 war er Bundesminister für Wirtschaft. Nach der Ermordung von Jürgen Ponto durch die Rote-Armee-Fraktion übernahm Friderichs dessen Position als Vorstandssprecher Dresdner Bank von 1978 bis 1985.',
      'Hans Karl Filbinger (1913-2007) war seit 1934 Mitglied der SA und seit 1937 Mitglieder bei der NSDAP, im März 1943 wurde er zum Marinerichter ernannt. Nach seiner Entlassung aus britischer Kriegsgefangenschaft war er als Rechtsanwalt tätig.',
      'Im Jahr 1951 trat Filbinger der CDU bei. Von 1966 bis 1978 bekleidete er das Amt des Ministerpräsidenten Baden-Württembergs. Außerdem war er von 1973 bis 1979 einer der stellvertretenden Bundesvorsitzenden der CDU.',
      'Nachdem bekannt wurde, dass Filbinger während der NS-Zeit Todesurteile als Marinerichter ausgesprochen hatte, trat er am 7.8.1978 als Ministerpräsident von Baden-Württemberg zurück.',
      'Der CDU-Politiker Karl Walter Klaus Carstens (1914-1992) war von 1972 bis 1979 Mitglied des Deutschen Bundestags, zwischen 1973 und 1976 als Vorsitzender der CDU/CSU-Bundesfraktion und Oppositionsführer, 1976 bis 1979 als Präsident des Deutschen Bundestages.',
      'Auch schon vor seiner Zeit als Bundestagsabgeordneter hatte er wichtige öffentliche Ämter bekleidet, u. a. war er Staatssekretär im Bundesministerium der Verteidigung von 1966 bis 1968. Den Höhepunkt seiner Karriere erreichte er aber im Jahr 1979 mit der Wahl zum fünften Bundespräsidenten der Bundesrepublik Deutschland.',
      'Rainer Barzel (1924-2006) war von 1957 bis 1987 Mitglied des Deutschen Bundestages. Im Jahr 1960 wurde er in den Bundesvorstand der CDU gewählt, 1962 zum Bundesminister für gesamtdeutsche Fragen in die Bundesregierung berufen, 1964 bis 1973 war er Fraktionsvorsitzender der CDU/CSU-Bundestagsfraktion.',
      'Unter Bundeskanzler Helmut Kohl wurde er 1982 als Bundesminister für innerdeutsche Beziehungen in das Kabinett berufen. 1983 bis 1984 war er Bundestagspräsident.',
      'Helmut Kohl (1930-2017) war von 1982 bis 1998 sechster Bundeskanzler der Bundesrepublik Deutschland. Der CDU-Politiker war zuvor zwischen 1969 und 1976 Ministerpräsident des Landes Rheinland-Pfalz.',
      'Im Jahr 1976 trat er bereits als Bundeskanzlerkandidat der CDU/CSU an und verlor gegen Helmut Schmidt, der am 1.10.1982 nach einem konstruktiven Misstrauensvotum aus dem Amt schied.',
      'Kurt Biedenkopf (1930-2021) war von 1973 bis 1977 Generalsekretär der CDU. Von 1976 bis 1980 gehörte er dem Deutschen Bundestag an.',
      'Er war überdies der erste Ministerpräsident Sachsens nach der Wiedervereinigung von 1990 bis 2002. Dem Landtag gehörte er bis 2004 an. Turnusmäßig war er von 1999 bis 2000 Bundesratspräsident.',
      'Hans Katzer (1919-1996) war 1945 Mitbegründer der Kölner CDU. Von 1957 bis 1980 war er Mitglied des Deutschen Bundestages, von 1969 bis 1979 stellvertretender Vorsitzender der CDU/CSU-Bundestagsfraktion.',
      'Im Kabinett Ludwig Erhards wurde er 1965 Bundesminister für Arbeit und Sozialordnung. In den Jahren 1972 und 1976 gehörte er zu den Schattenkabinetten von Rainer Barzel und Helmut Kohl.',
      'Alfred Dregger (1920-2002) war von 1956 bis 1970 Oberbürgermeister Fuldas. In den Jahren 1962 bis 1972 war er Mitglied des Hessischen Landtages sowie von 1972 bis 1998 Mitglied des Deutschen Bundestages.',
      'Von 1982 bis 1991 war er außerdem Vorsitzender der CDU/CSU-Bundestagsfraktion.',
      'Gerhard Stoltenberg (1928-2001) war als CDU-Politiker jahrelanges Mitglied des Landtages von Schleswig-Holstein (1954–1957; 1971–1982) sowie des Deutschen Bundestages (1957-1971; 1983-1998).',
      'In den Jahren 1969 bis 1971 hatte er das Amt des stellvertretenden Vorsitzenden der CDU/CSU-Bundestagsfraktion inne. 1971 wurde er schleswig-holsteinischer Ministerpräsident und blieb es bis 1982.',
      'Schon von 1969 bis 1971 hatte er unter der Regierung Ludwig Erhards das Amt des Bundesministers für wissenschaftliche Forschung bekleidet, 1982 wurde er unter Kohls Regierung wieder zum Minister ernannt, zunächst für Finanzen (1982–1989), dann für Verteidigung (1989–1992).',
      'Heinrich Köppler (1925-1980) schloss 1943 das Abitur ab und absolvierte anschließend eine Laufbahn als Berufssoldat. Nach dem Zweiten Weltkrieg und US-amerikanischer Kriegsgefangenschaft engagierte er sich für Kirche und Politik. So war er seit 1946 Mitglied der CDU und legte dort eine steile Karriere hin:',
      'Von 1969 bis 1980 war er Landesvorsitzender der CDU Rheinland, von 1971 bis 1980 Vorsitzender des Präsidiums der CDU NRW, von 1973 bis 1980 außerdem stellvertretender Vorsitzender der CDU auf Bundesebene sowie von 1965 bis 1970 Mitglied des Deutschen Bundestages.',
      'Des Weiteren war er von 1969 bis 1970 Parlamentarischer ‚Geschäftsführer der CSU/CDU Bundestagsfraktion.',
      'Kurt Georg Kiesinger (1904-1988) war von 1966 bis 1969 Bundeskanzler der Bundesrepublik Deutschland. In der Zeit von 1949 bis 1959 sowie von 1969 bis 1980 war er Mitglied des Deutschen Bundestages.',
      'Von 1958 bis 1966 war er Ministerpräsident von Baden-Württemberg, von 1967 bis 1971 Bundesvorsitzender der CDU. Kiesinger war von 1933 bis 1945 NSDAP-Mitglied – eine Vergangenheit, die vor allem in den 1960er Jahren zunehmend in die öffentliche Kritik geriet und in der ‚Kiesinger’Ohrfeige‘ mündete.',
      'Hanns Martin Schleyer (1915-1977) trat 1970 der CDU bei und galt als typischer Vertreter des politischen Unternehmers. Als Industriemanager und Verbandsfunktionär prägte er die noch junge Bundesrepublik.',
      'Die Entführung und Ermordung Schleyers durch das RAF-Kommando „Siegfried Hausner“ im September/Oktober 1977 ist einer der traurigen Höhepunkte des sogenannten ‚Deutschen Herbstes‘.',
      'Der Bundestagswahl von 1976 ging ein harter Wahlkampf voraus. Im Mittelpunkt standen die beiden Kanzlerkandidaten Helmut Kohl (CDU/CSU) und Helmut Schmidt (SPD). Der Wahlkampfslogan der CDU „Freiheit statt Sozialismus“ polarisierte ebenso wie jener der CSU: „Freiheit oder Sozialismus“.',
      'Darauf bezog sich auch die Devise des Plakats: „Diese Freiheit nicht! Demokraten wählen SPD.“',
      'Am 3. Oktober 1976 erhielt die CDU gemeinsam mit der CSU mit 48.6 Prozent der Stimmen ihr bestes Ergebnis seit 1957 und wurde so die stärkste Fraktion im Bundestag.',
      'Die SPD erhielt 42,6 Prozent, doch zusammen mit der FDP, die 7,9 Prozent erhielt, konnte sich die sozial-liberale Koalition knapp durchsetzen, sodass Helmut Schmidt das Amt des Bundeskanzlers behielt.',
    ],
    sources: [
      {
        text: 'LeMO: Geteiltes Deutschland: Spiegel-Affäre',
        link: 'https://www.hdg.de/lemo/kapitel/geteiltes-deutschland-modernisierung/bundesrepublik-im-wandel/spiegel-affaere.html',
      },
      {
        text: 'Bundeszentrale für politische Bildung: kurz&knapp - Das junge Politik-Lexikon: Rote Armee Fraktion',
        link: 'https://www.bpb.de/kurz-knapp/lexika/das-junge-politik-lexikon/321067/rote-armee-fraktion-raf/',
      },
    ],
  },
  environment: {
    header: 'Demo gegen THTR-Probelauf',
    texts: [
      'Mit der Bekanntgabe des Baus eines Thorium-Hochtemperaturreaktor (THTR) in Hamm formierten sich erste lokale Proteste und schließlich, 1975/1976, eine Bürgerinitiative. Bis 1982 fanden einige Aktionstage und Demonstrationen mit bis zu 1500 Teilnehmer*innen, ob jung oder alt, statt.',
      'Störfälle im THTR markierten im Jahr 1986 einen Wendepunkt in der Geschichte des Widerstandes gegen den Reaktor und die Proteste wurden lautstärker. Bei dieser Demonstration 1986 gingen rund 3000 Bürger*innen gemeinsam auf die Straße.',
      'Der Großteil der Demonstrant*innen stammte aus Hamm, das überregionale Interesse hielt sich in Grenzen. Dennoch galt die Demonstration als ein großer Erfolg.',
      'Zu sehen ist eine „Bierhalle“ bzw. Trinkhalle, wie sie typisch für das Ruhrgebiet ist. Die Aufschrift „Isenbeck“ offenbart auch den Standort: „Isenbeck“ ist eine beliebte lokale Premium-Marke in Hamm und Umgebung.',
      'Das Plakat stammt von der Bürgerinitiative Umweltschutz Hamm e. V. und ruft zu einer Demonstration gegen das Atomkraftwerk in Hamm-Werries am 17.9.1986 auf.',
      'Einige Zeit zuvor kam es mit der Nuklearkatastrophe von Tschernobyl am 26.4.1986 zur größten nuklearen Havarie des 20. Jahrhunderts.',
      'Kurz darauf, am 4.5.1986, drang aus dem Reaktor in Hamm radioaktiver Grafitstaub in die Umgebungsluft.',
      'Wie viel strahlendes Material ausgetreten ist, ließ sich nicht nachvollziehen, da zu diesem Zeitpunkt das Messinstrument abgeschaltet war. Dieser Vorfall wäre meldepflichtig gewesen – wurde aber von den Betreibern, der Hochtemperatur-Kernkraftwerk GmbH, des THTR verschwiegen',
      'Die Bürgerinitiative Hamm e. V. hat erfolgreich gegen den THTR gekämpft und existiert sogar bis heute! Unermüdlich setzt sie sich für die Aufklärung der risikoreichen Atomenergieversorgung ein und informiert in diesem Kontext über das atomökonomische und politische Geschehen weltweit in ihrem Newsletter.',
      'Grafisch dargestellt ist hier der Thorium- Hochtemperaturreaktor, kurz THTR-300, im nordrhein-westfälischen Hamm/Uentrop. Die Bauarbeiten am Kernkraftwerk THTR-300 begannen 1970 und wurden 1985 beendet.',
      'Anstelle von Brennstäben wurden in diesem Reaktor Graphitkugeln verwendet – damit folgte man dem 1967 in Betrieb genommenen Prototypen Arbeitergemeinschaft Versuchsreaktor Jülich (AVR).',
      'Bereits am AVR Jülich kam es 1978 zu einem Störfall. Im THTR häuften sich etliche nicht meldepflichtige und 21 meldepflichtige Vorfälle. Der dabei entstandene Kugelbruch beziehungsweise radioaktive Grafitstaub befindet sich gegenwärtig immer noch in unbekannter Menge im Reaktor und erschwert den Rückbau des Kernkraftwerks enorm.',
      'Im September 1989 wurde der Betrieb aus sicherheitstechnischen und wirtschaftlichen Gründen eingestellt. Es verwundert also überhaupt nicht, dass der Dampf aus dem Atomkraftwerk in Form eines Totenkopfes emporsteigt.',
      'Na, aufgefallen? Hier fehlt noch ein R!',
    ],
    sources: [
      {
        text: 'Rundbrief THTR der Bürgerinitiative Hamm e.V.',
        link: 'https://www.reaktorpleite.de/',
      },
      {
        text: 'Isenbeck Firmengeschichte',
        link: 'https://isenbeck.de/historie/',
      },
      {
        text: 'Geschichte - Wie war das noch damals mit dem THTR?',
        link: 'https://www.reaktorpleite.de/geschichte.html#Fakten',
      },
      {
        text: 'Rückblick: 15 Jahre Bürgerinitative Umweltschutz Hamm',
        link: 'https://www.machtvonunten.de/lokales-hamm/192-rueckblick-15-jahre-buergerinitative-umweltschutz-hamm.html',
      },
      {
        text: 'Arndt, Melanie: Tschernobyl. Auswirkungen des Reaktorunfalls auf die Bundesrepublik Deutschland und die DDR, Landeszentrale für politische Bildung, Thüringen 2011.',
        link: '',
      },
    ],
  },
  peace: {
    header: 'There´s no Space',
    texts: [
      'Ursprünglich geht das Symbol der Friedenstaube auf die Geschichte Noahs aus dem Alten Testament zurück.',
      'Als Symbol der Friedensbewegungen ist sie aber auch mit dem Künstler Pablo Picasso (1881–1973) verbunden:',
      'Picasso, engagiertes Mitglied der kommunistischen Partei, gestaltete seit 1949 mit der Friedenstaube Plakate in Breslau, Paris, Stockholm, Sheffield und Rom.',
      'Mit seinen Arbeiten drückte er seine eigene politische Haltung künstlerisch aus, propagierte die Friedensbewegung und protestierte gegen Krieg und Unterdrückung.',
      'Die Friedenstaube als Astronautin ist nur eine, wenn auch ungewöhnliche Variante dieses wohl bekanntesten Hoffnungssymbols.',
      'Die Auftraggeberin dieses Plakates ist die World Federation of Democratic Youth (WFDY).',
      'Der Weltbund der Demokratischen Jugend wurde 1945 gegründet, ihm gehören mittlerweile 150 Mitgliedorganisationen aus 109 Ländern an mit insgesamt 30 Millionen Jugendlichen. Die WFDY ist sozialistisch ausgerichtet.',
      'Das Plakat „There’s no space for weapons in Space“ entstammt der Kampagne gegen die Stationierung von Waffen- und Aufklärungssystemen im Weltall in den 1980er Jahren.',
      'Inmitten des Kalten Krieges war so eine neue Qualität des Wettrüstens erreicht: Waffen nicht nur auf der Erde, sondern auch im Weltall zu stationieren.',
    ],
  },
  peace2: {
    header: 'Plakat 6 vor 12',
    texts: [
      'Am 21./22. November 1983 wurde im Deutschen Bundestag über die Stationierung von 108 Pershing II-Raketen und 96 Marschflugkörpern auf deutschem Territorium entschieden.',
      'Die Abgeordneten von CDU/CSU und FDP stimmten mit einem JA für die Stationierung neuer Atomwaffen in der BRD.',
      'Der Countdown zeigt Sechs an: Herbert Werner (geb. 1941) studierte nach dem Abitur Geschichte und Englisch an der Universität Tübingen und am University College of North Wales.',
      'Danach war er als Assessor, anschließend als Studienrat und später als Oberstudienrat am Humboldt-Gymnasium Ulm tätig.',
      'Im Jahr 1969 trat Werner in die CDU und in die Junge Union ein. In der 7. bis 12. Wahlperiode (1972–1994) vertrat er den Wahlkreis 173 bzw. 195 (Ulm) im Bundestag.',
      'Der Countdown zeigt Fünf an: Hermann Schwörer (1922-2017). Nachdem er im Jahr 1940 das Abitur bestand, begann er in Tübingen das Studium der Rechts- und Staatswissenschaften. Unterbrochen wurde das Studium durch Schwörers Einberufung zur Wehrmacht 1941.',
      '1945 setzte er das Studium fort. 1950 wurde er zum Dr. jur. promoviert und trat im selben Jahr in den familieneigenen Baustoffbetrieb ein. Im Jahr 1951 wurde er CDU-Mitglied und rückte 1958 für den verstorbenen Abgeordneten Herbert Wolff in den Bundestag nach.',
      'In der 5. bis 8. Wahlperiode (1965-1980) vertrat Schwörer den Wahlkreis 197 (Balingen), in der 9. bis12. Wahlperiode (1980-1994) den Wahlkreis 198 (Zollernalb-Sigmaringen). In der 3. Wahlperiode engagierte er sich unter anderem seit November 1958 im Ausschuss für Atomkernenergie und Wasserwirtschaft.',
      'Der Countdown zeigt Vier an: Manfred Abelein (1930-2008) studierte nach dem Abitur Rechtswissenschaft, Volkswirtschaft und Politikwissenschaft und wurde im Jahr 1954 zum Dr. jur. an der Universität Basel promoviert.',
      'Als CDU-Abgeordneter des Wahlkreises 174 (Aalen-Heidenheim) gehörte er von 1965 bis 1990 dem Bundestag der 5. bis11. Wahlperiode an.',
      'Der Countdown zeigt Drei an: Elmar Kolb (1936-2013). Er absolvierte eine kaufmännische Lehre und studierte von 1958 bis 1961 Maschinenbau am Ohm-Polytechnikum in Nürnberg. Im Jahr 1965 trat er der Jungen Union bei und 1967 der CDU.',
      'Seit 1969 gehörte Kolb dem Bezirksvorstand der CDU, Süd-Württemberg-Hohenzollern, an. Im Jahr 1977 rückte er für den ausgeschiedenen Abgeordneten Norbert Nothhelfer in den Bundestag nach.',
      'Über die CDU-Landesliste Baden-Württemberg wurde er 1980 in den Bundestag gewählt und vertrat in der 10. und 11. Wahlperiode (1983–1990) den Wahlkreis 197 (Ravensburg – Bodensee) im Bundestag. Unter anderem gehörte er dem Ausschuss für Umwelt, Naturschutz und Reaktorsicherheit (seit Juni 1986) an.',
      'Der Countdown zeigt Zwei an: Hans-Peter Repnik (geb. 1947) studierte nach dem Abitur und dem Wehrdienst Rechts- und Staatswissenschaften an der Universität Freiburg.',
      'Nachdem er sich in den 1970er Jahren erst in der Jungen Union und später in der CDU engagierte, war er von 1989 bis 1994 Parlamentarischer Staatssekretär beim Bundesminister für wirtschaftliche Zusammenarbeit und Entwicklung.',
      'Zwischen 1980 und 2005 vertrat er den Wahlkreis 191 (Konstanz) im Bundestag. Repnik war von 2010 bis 2012 Mitglied und Vorsitzender des Rates für Nachhaltige Entwicklung.',
      'AUS: Der Atompilz von „Fat Man“ über steht sinnbildlich für die US-amerikanischen Atombombenabwürfe auf Hiroshima und Nagasaki am 6.8.1945 und 9.8.1945.',
      'Insgesamt töteten die Atombombenexplosionen circa 100.000 Menschen. An den Folgeschäden starben allein bis Ende 1945 weitere 130.000 Menschen. In den Jahren danach stieg die Zahl der Opfer ins Exorbitante.',
      'Den Befehl zum Abwurf der Atombomben gab der amerikanische Präsident Harry S. Truman. Am 2.9.1945 endete der Zweite Weltkrieg mit der Kapitulation Japans auch in Asien.',
      'Trotz der Atombombenabwürfe auf Hiroshima und Nagasaki entstand durch propagierte Trennung zwischen ziviler und militärischer Atomenergienutzung eine Gleichzeitigkeit von Atomeuphorie und Atomangst.',
      'Die metaphorische Weltuntergangsuhr beziehungsweise Atomkriegsuhr soll der Öffentlichkeit verdeutlichen, wie groß das Risiko einer globalen Katastrophe insbesondere im Hinblick auf einen Atomkrieg oder einer Klimakatastrophe ist.',
      'Die Politikerporträts auf dem Plakat tragen allesamt eine Zahl von 6 bis 2 im linken unteren Winkel. Diese Zahlen markieren das Herunterzählen von 6 bis 1.',
      'In dem mit 1 bezifferten Bild explodiert schließlich die Atombombe und der Countdown endet mit der „atomaren Katastrophe“.',
    ],
    sources: [
      {
        text: 'Deutsche Welle: Trotz großer Proteste: Der NATO-Doppelbeschluss 1983',
        link: 'https://www.dw.com/de/trotz-gro%C3%9Fer-proteste-der-nato-doppelbeschluss-1983/a-3807290',
      },
      {
        text: 'Rudolf Vierhaus, Ludolf Herbst (Hrsg.), Bruno Jahn (Mitarb.): Biographisches Handbuch der Mitglieder des Deutschen Bundestages. 1949–2002. Bd. 1: A–M. K. G. Saur, München 2002.',
        link: '',
      },
      {
        text: 'Rudolf Vierhaus, Ludolf Herbst (Hrsg.), Bruno Jahn (Mitarb.): Biographisches Handbuch der Mitglieder des Deutschen Bundestages. 1949–2002. Bd. 2: N–Z. Anhang. K. G. Saur, München 2002.',
        link: '',
      },
    ],
  },
  peace3: {
    header: 'Ostermarsch 1984',
    texts: [
      'Ganz schön viele verschiedene Menschen! Vom Kleinkind über Arbeiter*innen und Angestellte bis hin zu Rentner*innen sind diese illustrierten Menschen allen Alters und aller sozialen Schichten in einem vereint: in ihrem „Nein“ zum Rüstungswahn.',
      'Der Hintergrund dieser Demonstration ist die Zeit des NATO-Doppelbeschlusses aus dem Jahr 1979. In Westdeutschland kam es vermehrt zu Großdemonstrationen. Auch wenn oft jüngere Menschen die Mehrheit bei solchen Demonstrationen beziehungsweise Ostermärschen bildet, sind hier alle Altersklassen und Gesellschaftsschichten vertreten.',
      'Typisch für Friedensdemonstrationen sind die hier abgebildeten Fahnen, Transparente und Schilder mit der symbolischen Friedentaube oder beispielsweise kurzen Leitsprüchen wie „Nein zu Atom“.',
      'Der erste Ostermarsch in Deutschland fand im Jahr 1960 statt und führte als mehrtägiger Marsch von Hamburg über Bremen, Hannover und Braunschweig nach Bergen-Hohne.',
      'Bergen-Hohne war ein Raketenübungsgelände der Bundeswehr, wo, Berichten zufolge, eine Batterie Honest-John-Raketen mit atomaren Sprengköpfen stationiert worden war. Hieran nahmen circa 120 Teilnehmer*innen teil.',
      'Seitdem finden alljährlich rings um die Osterfeiertage bundesweit Ostermärsche statt, immer unter dem Motto: Für den Frieden und gegen Waffen.',
      'Insbesondere in den Jahren von 1979 bis 1990 kam es durch den NATO-Doppelbeschluss zu einem neuen Aufschwung der Ostermärsche.',
      '1984 nahmen so bundesweit circa 600.000 Menschen zum Abschluss der Ostermärsche an Kundgebungen für Abrüstung und Frieden teil.',
      'Die Pershing II war eine militärische Rakete aus US-amerikanischer Produktion, benannt nach dem US-General John Joseph Pershing. In Westdeutschland begann wenige Tage nach der Zustimmung des Deutschen Bundestag vom 22.11.1983 die Stationierung der Pershing II.',
      'Auf diesem Banner ist deutlich der Spruch „Stoppt den Rüstungswahn“ zu lesen. Dieser Leitspruch wurde und wird häufig bei pazifistischen und antimilitaristischen Demonstrationen und Ostermärschen genutzt. Im Jahr 1984 war die Situation aufgrund des NATO-Doppelbeschlusses und besonders besorgniserregend.',
      'Seit 1970 wurden die Raketen Pershing II und die Marschflugkörper Cruise Missiles entwickelt. Durch ihre Treffgenauigkeit und flexible Reichweite galten sie als technische Innovation.',
      'Im Dezember 1979 wurde von den Außen- und Verteidigungsministern der NATO-Mitgliedstaaten in Brüssel beschlossen, die Pershing II als auch die Cruise Missiles in Europa zu stationieren.',
      'Zeitgleich sollten der Sowjetunion aber Verhandlungen über eine beidseitige Reduzierung nuklearer Waffen angeboten werden.',
      'Diese Karikatur zeigt den ehemaligen deutschen Bundeskanzler Helmut Kohl (1930–2017), der von 1982 bis 1998 im Amt war. Kohl war nicht nur Gegenstand unzähliger Satiren, sondern auch von Karikaturen. Besonders oft wurde er als Birne karikiert, aber die Kopfform erinnerte auch an ein Ei.',
      'Und so wurde Kohl in diesem Plakat als „Eierkopf“ dargestellt –  eine umgangssprachliche Bezeichnung, die abwertend beziehungsweise ironisch für Intellektuelle genutzt wird.',
      'Ein Demonstrant tritt Helmut Kohl, dargestellt als „Eierkopf“, ins Gesicht, woraufhin seine ‚Schale‘ reißt. Dieser Akt der Gewalt gegen den (karikierten) Bundeskanzler symbolisiert die Wut und den Widerstand der Bevölkerung gegen die politischen Entscheidungen.',
      'Häufig sind auch ganz konkrete Aufforderungen und Informationen Teil eines Plakats. Denn: Woher sollten die Aktivist*innen ganz ohne Internet wissen, wann und wo es mit der Demo losgeht und welches Programm sie erwartet?',
      'Und so wird an dieser Stelle über den Ablauf des Ostermarsches informiert: Angefangen mit einer Blockade der US-Kaserne in der Garlstedter Heide vor Ostern war für den Ostersonntag ein Ostermarsch von Neuengamme (Standort eines ehemaligen Konzentrationslagers) nach Hamburg geplant.',
      'Aus allen Hamburger Stadtteilen sollten dann die Demonstrant*innen aus allen Himmelsrichtungen in Sternmärschen zum Rathausmarkt kommen. Dort fand dann die Abschlusskundgebung statt. Mit Unterstützung der Hamburger Stadtteilinitiativen war dann zwischen dem 24. und 28.8.1984 noch eine Aktionswoche betrieblicher Friedensinitiativen geplant – so konnte man sich auch gut einstimmen auf den schon bald folgenden Arbeiterkampftag am 1. Mai.',
      'Das Plakat stammt von den Jungsozialisten der SPD. Sie positionierten sich in den 1980er Jahren explizit gegen die Stationierung von Atomwaffen und gegen eine Politik der Aufrüstung. Von den Jusos gingen deshalb verschiedenste Aktionen aus, so etwa der Aufruf zum Ostermarsch in Hamburg wie hier.',
      'Die Friedensbewegung der 1980er Jahren brachte bis heute die größten Friedensdemos für Pazifismus und Antimilitarismus in der bundesdeutschen Geschichte mit sich.',
    ],
    sources: [
      {
        text: 'Deutscher Bundestag: Historische Debatten (9): Nato-Doppelbeschluss',
        link: 'https://www.bundestag.de/dokumente/textarchiv/natodoppelbeschluss-200098',
      },
      {
        text: 'Netzwerk Friedenskooperative: Größte Friedensdemos der bundesdeutschen Geschichte',
        link: 'https://www.friedenskooperative.de/friedensforum/artikel/groesste-friedensdemos-der-bundesdeutschen',
      },
      {
        text: 'Digitales Wörterbuch der deutschen Sprache: Eierkopf, der',
        link: 'https://www.dwds.de/wb/Eierkopf',
      },
      {
        text: 'Der Spiegel: Kohl-Karikaturen Die Rache der Birne',
        link: 'https://www.spiegel.de/geschichte/helmut-kohl-in-karikaturen-die-rache-der-birne-a-1037236.html',
      },
      {
        text: 'Was war wann? April 1984 - Ostermesse und Ostermärsche',
        link: 'https://www.was-war-wann.de/1900/1980/april-1984.html',
      },
      {
        text: 'Bethge; Horst: »Die Bombe ist böse.« Wie in Hamburg der Ostermarsch entstand, in: Berlin, Jörg (Hg.): Das andere Hamburg. Freiheitliche Bestrebungen in der Hansestadt seit dem Spätmittelalter, Köln 1981, S. 357-367.',
        link: '',
      },
      {
        text: 'Vierhaus, Rudolf; Herbst, Ludolf  (Hrsg.); Jahn, Bruno (Mitarb.): Biographisches Handbuch der Mitglieder des Deutschen Bundestages. 1949–2002. Bd. 1: A–M. K. G. Saur, München 2002.',
        link: '',
      },
    ],
  },
  solidarity: {
    header: 'Save their lives',
    texts: [
      '„Freedom for all political prisoners in Chile!“ – „Freiheit für alle politischen Gefangenen in Chile!“',
      'Der 11.9.1973 stellt eine Zäsur in der chilenischen Geschichte dar: Am Vormittag dieses Tages putschte das Militär unter der Führung des chilenischen Generals Augusto Pinochet (1915–2006) die Regierung des marxistisch-sozialistischen Präsidenten Salvador Allende (1908–1973).',
      'Das Militär brachte binnen kürzester Zeit das Land unter seine Kontrolle. Zweifelsfrei war dieser Putsch einer der brutalsten und systematischsten in Lateinamerika.',
      'Mehr als 27.000 Regimegegner*innen wurden verfolgt, gefangen genommen und gefoltert. Seitdem herrschte in Chile unter dem Diktator Pinochet 17 Jahre lang eine brutale Diktatur – eine der langlebigsten Militärdiktaturen der Neuzeit.',
      'Ursprünglich geht das Symbol der Friedenstaube auf die Geschichte Noahs aus dem Alten Testament zurück. Als Symbol der Friedensbewegungen ist sie aber auch mit dem Künstler Pablo Picasso (1881–1973) verbunden.',
      'Picasso, engagiertes Mitglied der kommunistischen Partei, gestaltete seit 1949 mit der Friedenstaube Plakate in Breslau, Paris, Stockholm, Sheffield und Rom. Mit seinen Arbeiten drückte er seine eigene politische Haltung künstlerisch aus, propagierte die Friedensbewegung und protestierte gegen Krieg und Unterdrückung.',
      'Während des Kalten Krieges wurde die Friedenstaube zu einem der wichtigsten Hoffnungssymbole.',
      'Die erhobene, geballte Faust steht für Solidarität, Stärke und Widerstand.',
      'Die Bücher wiederum deuten auf etwas anderes hin: das Recht auf Bildung und Aufklärung, Presse- und Meinungsfreiheit.',
      '„Save their lives“ – „Rette ihr Leben“ Die chilenische Militärdiktatur unter Augusto Pinochet herrschte von 1973 bis 1990 und hinterlässt eine traurige Menschenrechtsbilanz: 2.095 Ermordete oder Hingerichtete, 1.102 spurlos Verschwundene und circa 250.000 Exilierte.',
      'Die Auftraggeberin dieses Plakates ist die World Federation of Democratic Youth (WFDY). Der Weltbund der Demokratischen Jugend wurde 1945 gegründet, ihm gehören mittlerweile 150 Mitgliedorganisationen aus 109 Ländern an mit insgesamt 30 Millionen Jugendlichen.',
      'Die WFDY ist sozialistisch ausgerichtet. Deshalb wundert es auch nicht, dass die klassischen Symbole der linken Bewegungen hier wiederzufinden sind: die Friedenstaube, die erhobene Faust, das Buch.',
      'Das Ziel des Plakats ist es, auf die menschenunwürdigen Zustände innerhalb der chilenischen Diktatur unter Pinochet aufmerksam zu machen.',
    ],
    sources: [
      {
        text: 'Picasso: Fried | Picasso: Frieden und Freiheit',
        link: 'https://www.altertuemliches.at/termine/ausstellung/picasso-frieden-und-freiheit',
      },
      {
        text: 'SWR Wissen - Wie ist die Taube zum Friedenssymbol geworden?',
        link: 'https://www.swr.de/wissen/1000-antworten/wie-ist-die-taube-zum-friedenssymbol-geworden-100.html',
      },
      {
        text: 'Bundeszentrale für politische Bildung: Vom schwierigen Umgang mit dem Erbe der Pinochet-Diktatur',
        link: 'https://www.bpb.de/themen/mittel-suedamerika/lateinamerika/44689/vom-schwierigen-umgang-mit-dem-erbe-der-pinochet-diktatur/',
      },
      {
        text: 'Brandenburgische Landeszentrale für politische Bildung: Was ist eine Diktatur? ',
        link: 'https://www.politische-bildung-brandenburg.de/demokratie/was-ist-eine-diktatur',
      },
    ],
  },
  solidarity2: {
    header: 'Solidarität mit dem chilenischen Volk',
    texts: [
      'Dieses Plakat aus dem Jahr 1973 ist ein Nachdruck eines chilenischen Wahlplakats, in Auftrag gegeben von den Jungsozialisten der SPD und der Sozialistischen Jugend Deutschlands – Die Falken.',
      'Es fordert die Solidarität mit dem chilenischen Volk, nachdem der demokratisch gewählte, sozialistische Präsident Salvador Allende im September 1973 vom Militär geputscht wurde. Nach dem Putsch herrschte in Chile eine Militärdiktatur.',
      'Das Originalplakat stammt von der Radikalen Partei (Partido Radical) aus dem Jahr 1970. Die Radikale Partei ging aus dem radikalen Flügel der chilenischen Liberalen Partei hervor.',
      'Statt „Solidarität mit dem chilenischen Volk. Wahlkampfplakat aus Chile 1973: Vereinte Front gegen die Agression – immer mit der Linken –“ war im Original zu lesen: „B-18 M. Leon Prado; Diputado“. Das Originalplakat warb also für den Abgeordneten Miguel León Prado.',
      'Die Radikalen waren innerhalb der Unidad Popular, einem Wahlbündnis von linken chilenischen Parteien und Gruppierungen, auf Liste B vertreten – B-18 bezeichnete den Platz des Abgeordneten. Es ist zu vermuten, dass dieses Plakat auch für die Wahlwerbung anderer Abgeordneter genutzt wurde.',
      '„Unidad frente a la agresion“ bedeutet „Einheit gegen die Aggression“. Es ist ein Aufruf, sich als Bevölkerung zusammenzuschließen und eine Einheit zu bilden, um der militärischen Aggression zu entgegnen.',
      'Ein Seemann mit Pudelmütze, ein Arbeiter mit der Spitzhacke in der Hand, ein Vertreter der indigenen Bevölkerung, eine Arbeiterin und der Büroangestellte: All diese verschiedenen Menschen symbolisieren die Vielfalt von Chiles Bevölkerung, zugleich sollen sie die „Einheit des Volkes“ zum Ausdruck bringen.',
      'Die Hand, die über dem Volk schwebt, symbolisiert die Konterrevolution von rechts in Chile.',
      'Verdeutlicht wird dies durch verschiedene Symboliken wie das Hakenkreuz der Faschisten, den Stern der Nationalpartei, das Doppelkreuz der Christdemokraten, die Spinne der Terrororganisation „Vaterland und Freiheit“, den Hahn der rechtsradikalen Partei „Partido de Izqierda Radical“ (zu sehen auf dem Fingernagel) sowie die Sterne und Streifen der Flagge der USA.',
      '„Siempre a la izquierda“ bedeutet übersetzt: „Immer links“. Zu sehen ist hier zudem das Zeichen der Unidad Popular (UP) also der Radikalen Partei.',
      'Die UP wurde 1969 als ein Wahlbündnis von linken chilenischen Parteien beziehungsweise Gruppierungen gegründet. Im Jahr 1970 bekam Salvador Allende, Kandidat der Unidad Popular, bei den Präsidentschaftswahlen mit 36,3 % die meisten Stimmen.',
      'Kurz darauf wurde er vom Nationalkongress in einer Stichwahl zum chilenischen Präsidenten gewählt.',
    ],
    sources: [
      {
        text: 'Hagen, Waltraud; Jacobs, Peter: Salvador Allende. Eine Chronik, Berlin 2008.',
        link: '',
      },
      {
        text: 'Saavedra Santis, Omar; Wenzl, Ingrid: Chile. Ein anderer elfter September (Band 1), Berlin 2006.',
        link: '',
      },
    ],
  },
  youth: {
    header: 'Jugend für Ausländerfreundlichkeit',
    texts: [
      'An dieser Stelle ist das Logo des Jugendverbandes „SJD – Die Falken“ zu sehen, von dem das Plakat herausgegeben wurde. Die Falken setzen sich für mehr Demokratie, soziale Gerechtigkeit, Selbstbestimmung und Frieden. Mit diesem Plakat bezogen sie Anfang der 1990er Stellung gegen Rassismus und „Ausländerfeindlichkeit“.',
      'Hier ist eine rote Fahne zu sehen. Die rote Fahne ist ein Symbol der Arbeiterbewegung. Ihre Geschichte reicht weit zurück: Bereits im Zuge der Julirevolution 1830 etwa versammelten sich Arbeiter*innen einer Tuchfabrik unter ihr, um für bessere Bedingungen zu demonstrieren.',
      'Während der Revolutionen von 1848/49 gewann die rote Fahne größere Popularität. In den folgenden Jahrzehnten etablierte sie sich als Symbol der Arbeiterbewegung.',
      'Das Rot wurde oftmals als Symbol des blutigen Kampfes der Arbeiter*innen für ihre Rechte und Freiheiten interpretiert. Auch beim Schlesischen Weberaufstand 1844 versammelten sich die Arbeiter*innen unter einer roten Fahne. Durch die Revolutionsjahre 1848/49 gewann die rote Fahne größere Popularität. In den folgenden Jahrzehnten wurde die rote Farbe immer mehr zum Symbol der Arbeiterbewegung.',
      'Mit dem 1863 gegründeten Allgemeinen Deutschen Arbeiterverein (ADAV), welcher auch die Rote Fahne als Symbolik trug, wurde das Rot zur Farbe der Sozialdemokratie.',
      'In den Folgejahrzehnten wählten auch sozialistische und kommunistische Bewegungen die rote Fahne zu ihrem Symbol. In Deutschland haben daher sowohl die SPD als auch die Linke die Farbe Rot als prägende Parteifarbe.',
      'Auch Staaten, deren Gesellschaftsform Kommunismus oder Sozialismus ist, haben häufig einen roten Grundton in ihrer Flagge. Bis heute verwenden unterschiedliche Staaten, Parteien, Organisationen und Bewegungen die rote Fahne und stellen sich auf diese Weise in die Tradition der Arbeiterbewegung.',
      'Auf einem Transparent geschrieben steht hier die Parole „Dem Hass keine Chance“. Der Slogan plädiert für Vielfalt, Offenheit und Toleranz und setzt sich gegen Hass, Gewalt und Rassismus ein. Demonstrant*innen nutzen Transparente, um ihre Forderungen in die Öffentlichkeit zu tragen.',
      '„Internationale Solidarität – Jetzt“ – Solidarität bezeichnet ein Zusammengehörigkeitsgefühl von Individuen und Gruppen. Das Konzept der Solidarität erlebte sowohl innergesellschaftlich als auch auf internationaler Ebene in der zweiten Hälfte des 20. Jahrhunderts ihre Blütezeit.',
      'In der Arbeiterbewegung steht Solidarität für den Zusammenhalt der Arbeit*innen untereinander. Hiermit eng verbunden ist die internationale Solidarität, insbesondere die Beziehungen zwischen Industrie- und Entwicklungsländern.',
      'In den Jahren 1978-1979 kam es in Nicaragua zur sandinistischen Revolution. Der Diktator Anastasio Somoza wurde gestürzt und der linksorientierte Frente Sandinista de Liberación Nacional kam in an die Macht.',
      'Unterstützt durch die USA versuchten Konterrevolutionäre die Revolution während des Contra-Krieges (1981-1990) rückgängig zu machen und kämpften gegen die linksgerichtete sandinistische Regierung.',
      'Zu der Contra-Gruppierung gehörten Anhänger Somozas, Teile der bürgerlichen Opposition, Bauern, enttäuschte Sandinisten und Teile der indigenen Bevölkerung.',
      'Der Contra-Krieg dauerte bis 1990 an und forderte zahlreiche Todesopfer. Mit dem Ende des Krieges wurde der politischen Gewalt jedoch kein Ende gesetzt. Bis in die zweite Hälfte der 1990 Jahre starben knapp 2000 weitere Menschen.',
      'Der Begriff „Ausländerfeindlichkeit“ bezeichnet eine negative Einstellung gegenüber Ausländerinnen und Ausländern. Von Vorurteilen geprägt, werden die Ausländer*innen im eigenen Land ausgegrenzt und angefeindet.',
      'Der hier stehende Begriff „AusländerFREUNDlichkeit“ drückt das genaue Gegenteil aus und soll der „Ausländerfeindlichkeit“ und die Bedeutung, die dem Begriff zukommt, entgegenwirken.',
      'Die „Gelbe Hand“ ist ein Symbol für Toleranz und gegen Ausländerfeindlichkeit.',
      'Hinter dem Logo steht der Verein „Mach meinen Kumpel nicht an!“. Der Verein wurde am 18.11.1986 von dem Deutschen Gewerkschaftsbund und „ran“ in Düsseldorf gegründet und stellt somit einen der der ältesten antirassistischen Organisationen in Deutschland dar.',
      'Die „Gelbe Hand“ steht für das Engagement gegen Fremdenfeindlichkeit, Rassismus und Rechtsextremismus und spricht vor allem Jugendliche an.',
    ],
    sources: [
      {
        text: 'Bundeszentrale für politische Bildung: Kriege und Konflikte: Nicaragua',
        link: 'https://www.bpb.de/themen/kriege-konflikte/dossier-kriege-konflikte/54799/nicaragua/',
      },
      {
        text: 'Bundeszentrale für politische Bildung: kurz&knapp: Ausländerfeindlichkeit',
        link: 'https://www.bpb.de/kurz-knapp/lexika/pocket-politik/16332/auslaenderfeindlichkeit/',
      },
      {
        text: 'Deutscher Gewerkschaftsbund: Die Gelbe Hand: 25 Jahre gegen Rassismus',
        link: 'https://www.dgb.de/themen/++co++06ebe75c-e507-11e0-598f-00188b4dc422',
      },
      {
        text: 'Aus Politik und Zeitgeschichte (BpB): Internationale Solidarität (pdf)',
        link: 'https://www.bpb.de/medien/31231/1XOLT3.pdf',
      },
    ],
  },
  youth2: {
    header: 'BAFÖG Demo',
    texts: [
      'Mit „Eugen“ ist das ehemalige Abgeordnetenhochhaus des Bundestages in Bonn gemeint: Das vom Architekten Egon Eiermann geschaffene Hochhaus war als „Langer Eugen“ bekannt.',
      'Das Zittern von „Eugen“, dem Abgeordnetenhaus, meinte also, dass die Abgeordneten aufgrund der geplanten Demonstration am Zittern sind.',
      'Die Elefanten stellen hier die Studierendenschaft dar. Elefanten, als Herdentiere bekannt, stehen für Weisheit, Stärke und Zusammenhalt.',
      'Den Sprechblasen ist zu entnehmen, dass sie für den Erhalt des BAföG plädieren.',
      'Bonn war von 1949 bis 1990 Hauptstadt der Bundesrepublik Deutschland.',
      'In Anlehnung an den Bundeskanzler Helmut Kohl, der zur Zeit der Veröffentlichung des Plakates amtierte, wurde „Bundes“ durchgestrichen und durch „Birne“ ersetzt. Kohl wurde während seiner Amtszeit häufig als Birne karikiert.',
      'Außerdem kündigt das Plakat an dieser Stelle mit: „Wir kommen am 4. Dez.“ eine Demonstration an. Gemeint ist hiermit die BAföG-Demo in Bonn am 4.12.1989.',
      'Hintergrund dieser Demonstrationen war der Wechsel von einer sozialliberalen zu einer konservativ geführten Regierung ab 1982.',
      'Die sozialliberale Regierung hatte durch Hochschulneugründungen und finanzielle Unterstützungen für Schüler*innen und Studierende aus verschiedenen Bevölkerungsschichten den Zugang zu Bildung und damit die Bildungsgerechtigkeit und den sozialen Aufstieg gefördert.',
      'Mit dem Regierungswechsel 1982 änderte sich dies: Die Ausbildungsförderung für Schüler*innen wurde quasi abgeschafft und der Zugang zum BAföG nicht nur beschränkt, sondern auf ein Volldarlehen geändert. Das bedeutete für Studierende hohe Schulden mit Ende eines Studiums.',
      'Der Spruch „Bildung kein Privileg für Reiche“ prangert die Bildungsungerechtigkeit an.',
      'Vor allem jene jungen Menschen wurde der Zugang zur Bildung verwehrt, die von Haus aus nicht die nötige finanzielle Unterstützung erhielten.',
      'Auch heutzutage ist dieses Problem noch nicht gelöst. Initiativen wie ArbeiterKind.de engagieren sich für einen besseren Zugang zu Bildung für alle.',
    ],
    sources: [
      {
        text: 'Bundesministerium des Innern und für Heimat: Unsere Hauptstadt',
        link: 'https://www.bmi.bund.de/DE/themen/verfassung/staatliche-symbole/hauptstadt/hauptstadt-artikel.html',
      },
      {
        text: 'KuLaDig: Abgeordnetenhochhaus „Langer Eugen“',
        link: 'https://www.kuladig.de/Objektansicht.aspx?extid=O-21102-20111109-3',
      },
      {
        text: 'Friedrich Ebert Stiftung: 50 Jahre BAföG: Best Ager oder Veteran?',
        link: 'https://www.fes.de/feshistory/blog/50-jahre-bafoeg',
      },
      {
        text: 'Die gemeinnützige GmbH ArbeiterKind.de',
        link: 'https://arbeiterkind.de',
      },
    ],
  },
  youth3: {
    header: 'Kampf dem sozialen numerus clausus',
    texts: [
      'Der Numerus clausus (NC) ist die zahlenmäßige Beschränkung der Zulassung zu einem bestimmten Studienfach an einer Universität. Maßgeblich hierfür ist die Note der Allgemeinen Hochschulreife.',
      'Mit einem „sozialen“ NC ist aber etwas anderes gemeint! Es geht um das Hindernis für junge Menschen, sich ein Studium überhaupt leisten zu können!',
      'Die Darstellung erinnert an eine modernisierte Ritterrüstung, in den Fäusten je eine Rakete.',
      'Aus der Rüstung ragt der skizzierte Kopf eines Menschen hervor, der die Forderung „Bildung statt Rüstung!“ ruft und mit seiner geballten Faust die Metallrüstung durchbricht.',
      'Deutlich wird hier die Forderung nach einer Prioritätenverschiebung durch Einsparungen im Rüstungshaushalt und Unterstützungsmaßnahmen im Bildungssektor.',
      'Statt staatliche Gelder in die Rüstungsindustrie und die Konzerne zu stecken, fordert das Plakat mehr Geld für Bildung und Ausbildung!',
      'Das karikierte Schwein, bestückt mit Waffen und Munitionen, symbolisiert die Rüstungsindustrie. Die Kopfbedeckung spielt auf militärische Uniformen an. Die Nase erinnert an die Mündung einer doppelläufigen Schrotflinte.',
      'Die beiden Figuren schneiden mit Messer und Gabel an dem Schwein. Getreu dem Motto: „Auch ein Stück vom Kuchen abzubekommen“, fragen sie: „Schon mal was von Bildungshunger gehört?“',
      'Auch wenn der Zugang zu Bildung allen Menschen offenstehen sollte, gibt es in der Realität Grenzen: Ein Studium muss Mensch sich erst einmal leisten können.',
      'Um die materiellen Hürden einzureißen, forderte der SHB eine bessere Finanzierung für Studierende und mehr Mitbestimmung. 500,- DM sollten der erste Schritt in diese Richtung sein.',
      'Heute könnte man mit umgerechnet ca. 250 Euro kaum ein WG-Zimmer zahlen, geschweige denn seinen Lebensunterhalt bestreiten.',
      'Auch Studierende benötigen eine gesundheitliche Absicherung! Deshalb kämpfte der SHB nicht nur eine bessere Versorgung, sondern insgesamt für eine Reform und Vereinheitlichung der Krankenkassen.',
      'In den 1980er Jahren wurde es für Studierende zunehmend schwieriger, eine bezahlbare Wohnung zu finden. Privatisierungen und Spekulationsgeschäfte waren an der Tagesordnung. Ein Problem, das sich bis heute sogar noch deutlich verschlimmert hat.',
      'Die SHB forderte deshalb eine Verbesserung der Wohnungssituation für weniger finanzkräftige Studierende.',
      'Die Karikatur von Kuro verdeutlicht die soziale Ungleichheit auf dem Wohnungsmarkt: Auf der einen Seite die Wohnungseigentümer – veranschaulicht durch einen korpulente Mann –, auf der anderen Seite die Mieter*innen – karikiert als Tube, aus der noch der letzte Groschen Miete herausgequetscht wird.',
      'Der SHB prangerte das Missverhältnis, dass die Reichen immer reicher und die Armen immer ärmer werden, an.',
      'Der SHB verstand sich als Teil der Arbeiter*innenklasse und kämpfte vor allem für die Interessen von Studierenden aus dem Arbeiter*innenmilieu.',
      '„Vorwärts mit dem SHB!“ – Die Abkürzung SHB steht für den Sozialistischen Hochschulbund.',
      'Der bundesweite Studentenverband wurde im Jahr 1960 als Sozialdemokratischer Hochschulbund in Bonn gegründet und stand der SPD nah.',
      'Nachdem sich die SPD im Jahr 1971 vom SHB löste und die finanzielle Unterstützung strich, beschloss der SPD-Parteivorstand 1972 dem SHB den Namen „sozialdemokratisch“ zu entziehen.',
      'Aus diesem Grund wurde er 1972 in „Sozialistischer Hochschulbund“ umbenannt. Der SHB engagierte sich in der Hochschulpolitik, gegen die Berufsverbote und in der Friedensbewegung. 1992 löste sich der SHB auf.',
    ],
  },
}
