export const concert = {
  timeline: [
    {
      index: 0,
      key: 'internationale',
      year: 1871,
      title: 'Die Internationale (1871) - Billy Bragg',
      link: 'https://www.youtube.com/watch?v=9LbziknNpCE',
    },
    {
      index: 1,
      key: 'morgenrot',
      year: 1907,
      title: 'Dem Morgenrot entgegen (1907) - Hannes Wader',
      link: 'https://www.youtube.com/watch?v=NhVVLsRoyWE',
    },
    {
      index: 2,
      key: 'graben',
      year: 1926,
      title: 'Der Graben (1926) - Gisela May',
      link: 'https://www.youtube.com/watch?v=LHCxm3uUsQU',
    },
    {
      index: 3,
      key: 'einheitsfrontlied',
      year: 1934,
      title: 'Solidaritätslied (1934) - Hannes Wader',
      link: 'https://www.youtube.com/watch?v=7TAB-U71kiY',
    },
    {
      index: 4,
      key: 'moorsoldaten',
      year: 1934,
      title: 'Moorsoldaten (1934) - Hannes Wader',
      link: 'https://www.youtube.com/watch?v=-boCKJsDe5U',
    },
    {
      index: 5,
      key: 'blowininthewind',
      year: 1961,
      title: 'Blowin in the Wind (1961) - Bob Dylan',
      link: 'https://www.youtube.com/watch?v=MMFj8uDubsE',
    },
    {
      index: 6,
      key: 'rauchhaussong',
      year: 1972,
      title: 'Rauch-Haus-Song (1972) - Ton Steine Scherben',
      link: 'https://www.youtube.com/watch?v=NMiznsg5As0',
    },
    {
      index: 7,
      key: 'elpueblounido',
      year: 1973,
      title: 'El pueblo unido (1973) - Quilapayún',
      link: 'https://www.youtube.com/watch?v=kTLrFjYt8tA',
    },
    {
      index: 8,
      key: 'grandolavilamorena',
      year: 1974,
      title: 'Grandola, vila morena (1974) - José Afonso',
      link: 'https://www.youtube.com/watch?v=IVKf00VGjGM',
    },
    {
      index: 9,
      key: 'schreinachliebe',
      year: 1993,
      title: 'Schrei nach Liebe (1993) - Die Ärzte',
      link: 'https://www.youtube.com/watch?v=_ZMu3HAWAnE',
    },
    {
      index: 10,
      key: 'sagenein',
      year: 1993,
      title: 'Sage nein! (1993) - Konstantin Wecker',
      link: 'https://www.youtube.com/watch?v=PgIh4ok1WjY',
    },
  ],
}
