export const concert = {
  timeline: [
    {
      index: 0,
      key: 'internationale',
      year: 1871,
      title: 'Die Internationale',
      link: 'https://www.youtube.com/watch?v=9LbziknNpCE',
    },
    {
      index: 1,
      key: 'morgenrot',
      year: 1907,
      title: 'Dem Morgenrot entgegen',
      link: 'https://www.youtube.com/watch?v=NhVVLsRoyWE',
    },
    {
      index: 2,
      key: 'graben',
      year: 1926,
      title: 'Der Graben',
      link: 'https://www.youtube.com/watch?v=LHCxm3uUsQU',
    },
    {
      index: 3,
      key: 'solidaritaetslied',
      year: 1931,
      title: 'Solidaritätslied',
      link: 'https://www.youtube.com/watch?v=l1rcW0J581c',
    },
    {
      index: 4,
      key: 'einheitsfrontlied',
      year: 1934,
      title: 'Einheitsfrontlied',
      link: 'https://www.youtube.com/watch?v=7TAB-U71kiY',
    },
    {
      index: 5,
      key: 'moorsoldaten',
      year: 1934,
      title: 'Moorsoldaten',
      link: 'https://www.youtube.com/watch?v=-boCKJsDe5U',
    },
    {
      index: 6,
      key: 'rauchhaussong',
      year: 1972,
      title: 'Rauch-Haus-Song',
      link: 'https://www.youtube.com/watch?v=NMiznsg5As0',
    },
    {
      index: 7,
      key: 'elpueblounido',
      year: 1973,
      title: 'El pueblo unido',
      link: 'https://www.youtube.com/watch?v=kTLrFjYt8tA',
    },
    {
      index: 8,
      key: 'grandolavilamorena',
      year: 1974,
      title: 'Grandola, vila morena',
      link: 'https://www.youtube.com/watch?v=IVKf00VGjGM',
    },
    {
      index: 9,
      key: 'schreinachliebe',
      year: 1993,
      title: 'Schrei nach Liebe',
      link: 'https://www.youtube.com/watch?v=_ZMu3HAWAnE',
    },
    {
      index: 10,
      key: 'sagenein',
      year: 1993,
      title: 'Sage Nein!',
      link: 'https://www.youtube.com/watch?v=PgIh4ok1WjY',
    },
  ],
}
