export const slogans = [
  'Runter mit der Kohle, hoch mit dem Klimaschutz!',
  'No border, no nation, no coal power station!',
  'Ob Ost, ob West, nieder mit der Kohlepest!',
  'Leute lasst das Glotzen sein, reiht euch in die Demo ein!',
  'Wir sind hier, wir sind laut, weil ihr uns die Zukunft klaut!',
  'Wir sind hier, wir sind laut, weil ihr uns die Freiheit klaut!',
  'Wir sind hier, wir sind laut, weil man uns die Bildung klaut!',
  'Wir sind hier, wir sind laut, weil man uns die Zukunft klaut!',
  'Alerta, alerta, antifascista!',
  'Klimaschutz ist meine Wahl – für alle und überall!',
  'Another world is possible!',
  'Hoch die internationale Solidarität!',
  'Our world is not for sale!',
  'Brecht die Macht der Banken und Konzerne!',
  'Kapitalismus raus aus den Köpfen!',
  'Solidarisieren! Mitmarschieren!',
  'One solution – revolution!',
  'Gebt uns uns´re Freiheit wieder!',
  'Anonymität ist kein Verbrechen!',
  'Alles für alle und zwar umsonst!',
  'Gegen Staat und Kapital – alles für alle überall!',
  'Krieg dem Krieg überall!',
  'Frieden schaffen – ohne Waffen!',
  'Kein Gott, kein Staat, kein Patriachat!',
  'Nationalismus raus aus den Köpfen!',
  'Freiheit für alle politischen Gefangenen!',
  'Gleiche Arbeit, gleicher Lohn – Alles andre purer Hohn!',
  'Gegen Rechts hilft kein Sexismus, unsere Antwort: Feminismus!',
  'No border, no nation – no gentrification!',
  'No border, no nation – stop deportation!',
  'No border! No nation! Animal liberation!',
  'No border! No nation! Free education!',
  'Grenzen auf – überall – Stacheldraht zu Altmetall!',
  'Kein Mensch ist illegal – Bleiberecht überall!',
  'Nazis verpisst euch – keiner vermisst euch!',
  'Ohne V-Mann wärt ihr nur zu dritt!',
  'Es gibt kein Recht auf Nazipropaganda!',
  'Solidarität heißt Widerstand!',
  'Seenotrettung ist kein Verbrechen!',
  'Wir wollen keine Kohle, Klimaschutz jetzt!',
  'Bread! Education! Freedom!',
  'Say it loud, say it clear – refugees are welcome here!',
  'No hate, no fear – refugees are welcome here!',
  'Lieber solidarisch - als brutal & arisch!',
  'Gemeinsam gegen rechten Wahn - Traut Euch Leute, schliesst Euch an!',
  'Komm mach mit & werd aktiv - gemeinsam gegen rechten Mief!',
  'One struggle, one fight – human freedom, animal right!',
  'Für die Freiheit, für das Leben!',
  'Mehr Rüstung - mehr Waffen - werden keinen Frieden schaffen!',
  'Bildung für die Masse, finden wir klasse!',
  'Sozialabbau und Bildungsklau, die Antwort darauf ist Radau!',
  'Was wir wollen ist nicht viel: Selbstbestimmung ist das Ziel!',
  'Bildungsklau im ganzen Land – unsre Antwort: Widerstand!',
  'Allen Leuten recht getan ist Sauerkraut mit Lebertran!',
  'Alles schreitet fort, nur der Fortschritt nicht!',
  'Alle wollen zurück zur Natur - aber keiner zu Fuß!',
  'Alles wird besser, nichts wird gut!',
  "Das Leben gibt's gratis, der Rest ist käuflich!",
  "Die Welt erstickt in Plastiktüten, die Einkaufstasche kann's verhüten!",
  'Die Zeit zurückdrehen, hieße Milch aus Käse zu produzieren!',
  'Eine Kuh macht muh, viele Kühe machen Mühe!',
  'Energiesparer: heizt mit Meerwasser, das ist fast reines Öl!',
  'Global investieren - lokal ruinieren!',
  'Guter Staat ist teuer!',
  'Gut gemeint ist auch nicht besser!',
  'High sein, frei sein, bloß in keiner Partei sein!',
  'Kein Abriss unter dieser Nummer!',
  'Wir kommen nicht in die Hölle. Wir leben schon drin!',
  'Liebe deinen Nächsten wie dein Auto!',
  'Lieber fernsehmüde als radioaktiv!',
  'Lieber süßen Nebel als sauren Regen!',
  'Ohne Lärm und viel Gebrüll macht das Blatt sein Chlorophyll!',
  'Sauer macht lustig, der Wald lacht sich schon kaputt!',
  'Schlanker Staat - dicker Profit!',
  'Tausche betonierte Zukunft gegen blühende Vergangenheit!',
  'Wer den Feind umarmt, macht ihn bewegungsunfähig!',
  'Wer den Schaden hat, braucht für den Schrott nicht zu sorgen!',
  'Wer nichts weiß, muss alles glauben!',
  'Wer zuletzt lacht, hat es nicht früher begriffen!',
  'Arbeitskraft? Nein danke!',
  'Atomkraft? Nein danke!',
  'Keine Macht für Niemand!',
  'Unter den Talaren – Muff von 1000 Jahren!',
  'Macht kaputt, was euch kaputt macht!',
  'Wer kämpft, kann verlieren; wer nicht kämpft, hat schon verloren!',
  'Der Klügere gibt so lange nach, bis er der Dumme ist!',
  'Nieder mit der Schwerkraft, es lebe der Leichtsinn!',
  'Wer zu viel fernsieht, verliert den Weitblick!',
  'Unter dem Pflaster liegt der Strand!',
  'Kein Gott, kein Staat, kein Patriarchat!',
  'Ehe, Küche, Vaterland – unsre Antwort Widerstand!',
  'Schlechtes Wetter, harte Zeiten – für den Feminismus streiten!',
  'Lasst es glitzern, lasst es knallen – Sexismus in den Rücken fallen!',
  'Egal ob queer oder hetero – antisexistisch sowieso!',
  'Das Mackertum könnt ihr euch schenken! Gegen jedes Rollendenken!',
  'Gegen Sexismus und Transphobie – Für den Feminismus und die Anarchie!',
  'Alerta, alerta, antisexista!',
  'Brick by brick, wall by wall, make the fortress Europe fall!',
  'Grenzen auf, überall, Stacheldraht zu Altmetall!',
  'No border, no nation, stop deportation!',
  'Wer schweigt, stimmt zu, lasst Rassisten nicht in Ruh’!',
  'Nazis morden, der Staat schaut zu – Verfassungsschutz und NSU!',
  'Ihr habt den Krieg verloren!',
  'Siamo tutti antifascisti!',
  'Es gibt kein Recht auf Nazipropaganda!',
  'Nationalismus raus aus den Köpfen!',
  'Alarmstufe rot. Die Erde schwitzt sich tot!',
  'Atomkraft ist scheiße – in Japan gibt’s Beweise!',
  'Banken retten, das geht fix. Für die Umwelt tut ihr nix!',
  'Das Wandern ist des Menschen Frust. Der Wald kaputt, der Rest verrußt!',
  'Die nächste Generation bezahlt – denn der Castor strahlt und strahlt!',
  'Es gibt kein Recht auf´s Kohlebaggerfahren!',
  'Es gibt kein Recht, die Umwelt zu zerstören!',
  "Greta sitzt vor'm Parlament – weil sie die Gefahr erkennt!",
  'In Zeiten wie diesen, betoniert man Wiesen!',
  "Kohletabletten sind für'n Magen – mehr erneuerbare Energie wagen!",
  'Kumpel, lass das Graben sein! Strom schickt uns der Sonnenschein!',
  'Lasst die Kohle in dem Boden. Niemand soll die Wälder roden!',
  'Lieber heute aktiv als morgen radioaktiv!',
  'Our goal: end coal!',
  "Populismus gehört abgeschafft. Experten komm' aus der Wissenschaft!",
  'Rettet die Pole! Raus aus der Kohle!',
  'Rohstoffmangel gibt es nie – bei Wind und Sonnenenergie!',
  'Save our land, save our sea! There ist no Planet B!',
  'Solidarität und Widerstand. Stoppt Kohlekraft in jedem Land!',
  'Stromerzeugung in diesem Land, gehört in genossenschaftliche Hand!',
  'Think global, act local – now!',
  "Tschernobyl und Fukushima – Unfälle komm' immer wieder!",
  'Umweltschutz statt Kohleschmutz!',
  "Was wir woll'n, sind nicht Krawalle – Energiegerechtigkeit für alle!",
  'Wehrt euch, leistet Widerstand – gegen die Atomkraft hier im Land!',
  'Weniger Asphalt, mehr Wald!',
  'Wieso? Weshalb? Warum? Wer noch gräbt, ist dumm!',
  'Wir sind hier, wir sind laut. Damit ihr Ökostrom für alle baut!',
  'Wir sind hier, wir sind laut. Weil ihr uns die Zukunft klaut!',
  "Ich sag' Kohle, ihr sagt Stopp!",
  "Ich sag' Klima, ihr sagt Schutz!",
  'In jeder Schule, in jedem Land – Widerstand, Widerstand!',
  "Für das Klima, unser'n Kampf – Widerstand, Widerstand!",
  'Uns´re Zukunft, wir sind dran – Widerstand, Widerstand!',
  'What do we want? – Climate justice!',
]
